action_id: trunk-cache-prune
date: 2024-01-19 19:49:04
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 0
  out: "\x1b[1m\x1b[30m\x1b[107m  PRUNE  \x1b[0m\r\n\r\n \x1b[1m\x1b[4mPath\x1b[22m\x1b[24m             \x1b[1m\x1b[4mFiles Removed\x1b[22m\x1b[24m  \x1b[1m\x1b[4mBytes Removed\x1b[22m\x1b[24m  \x1b[1m\x1b[4mFiles Remaining\x1b[22m\x1b[24m  \x1b[1m\x1b[4mBytes Remaining\x1b[22m\x1b[24m\r\n C:\\Users\\laptop  0              0 B            0                0 B            \r\n  \\AppData\\Local                                                                \r\n  \\Temp\\trunk                                                                   \r\n C:\\Users\\laptop  0              0 B            0                0 B            \r\n  \\AppData\\Local                                                                \r\n  \\trunk\\repos                                                                  \r\n  \\f94fcaa141fad                                                                \r\n  2a49de56a0b843                                                                \r\n  67e68\\out                                                                     \r\n\r\n\x1b[1m\x1b[92m✔ Removed 0 files totaling 0 B\x1b[0m\r\n"
  err: ""
timestamp: 1705693744
full_timestamp:
  nanos: 198024000
  seconds: 1705693744
trunk_version: 1.19.0
