# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'admin.ui'
##
## Created by: Qt User Interface Compiler version 6.6.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDateEdit, QHeaderView,
    QLabel, QLineEdit, QListView, QListWidget,
    QListWidgetItem, QMainWindow, QMenu, QMenuBar,
    QPushButton, QSizePolicy, QStatusBar, QTabWidget,
    QTableWidget, QTableWidgetItem, QTextEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1210, 820)
        self.menu11 = QAction(MainWindow)
        self.menu11.setObjectName(u"menu11")
        self.menu12 = QAction(MainWindow)
        self.menu12.setObjectName(u"menu12")
        self.menu21 = QAction(MainWindow)
        self.menu21.setObjectName(u"menu21")
        self.menu22 = QAction(MainWindow)
        self.menu22.setObjectName(u"menu22")
        self.menu31 = QAction(MainWindow)
        self.menu31.setObjectName(u"menu31")
        self.menu41 = QAction(MainWindow)
        self.menu41.setObjectName(u"menu41")
        self.menu42 = QAction(MainWindow)
        self.menu42.setObjectName(u"menu42")
        self.menu32 = QAction(MainWindow)
        self.menu32.setObjectName(u"menu32")
        self.menu33 = QAction(MainWindow)
        self.menu33.setObjectName(u"menu33")
        self.menu51 = QAction(MainWindow)
        self.menu51.setObjectName(u"menu51")
        self.menu61_a = QAction(MainWindow)
        self.menu61_a.setObjectName(u"menu61_a")
        self.menu71 = QAction(MainWindow)
        self.menu71.setObjectName(u"menu71")
        self.actionCheck_Reports = QAction(MainWindow)
        self.actionCheck_Reports.setObjectName(u"actionCheck_Reports")
        self.actionAccess_All_Functions = QAction(MainWindow)
        self.actionAccess_All_Functions.setObjectName(u"actionAccess_All_Functions")
        self.actionLesson_Attendance = QAction(MainWindow)
        self.actionLesson_Attendance.setObjectName(u"actionLesson_Attendance")
        self.actionMeeting_Schedule = QAction(MainWindow)
        self.actionMeeting_Schedule.setObjectName(u"actionMeeting_Schedule")
        self.actionMeeting_Attendance = QAction(MainWindow)
        self.actionMeeting_Attendance.setObjectName(u"actionMeeting_Attendance")
        self.actionAdd_Edit_To_Do_List = QAction(MainWindow)
        self.actionAdd_Edit_To_Do_List.setObjectName(u"actionAdd_Edit_To_Do_List")
        self.actionAdd_Edit_Announcement = QAction(MainWindow)
        self.actionAdd_Edit_Announcement.setObjectName(u"actionAdd_Edit_Announcement")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(0, 0, 1211, 51))
        font = QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setStrikeOut(False)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(u"color: rgb(253, 189, 16);\n"
"background-color: rgb(40, 41, 44);")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 50, 1221, 741))
        font1 = QFont()
        font1.setPointSize(10)
        font1.setBold(True)
        self.tabWidget.setFont(font1)
        self.tabWidget.setStyleSheet(u"background-color: rgb(40, 41, 44);")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.label_14 = QLabel(self.tab_3)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(520, 150, 171, 20))
        font2 = QFont()
        font2.setPointSize(11)
        font2.setBold(True)
        font2.setUnderline(True)
        self.label_14.setFont(font2)
        self.label_14.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_13 = QLabel(self.tab_3)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(210, 70, 851, 61))
        font3 = QFont()
        font3.setPointSize(26)
        font3.setBold(True)
        font3.setStrikeOut(False)
        self.label_13.setFont(font3)
        self.label_13.setStyleSheet(u"color: rgb(253, 189, 16);\n"
"background-color: rgb(40, 41, 44);")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.label = QLabel(self.tab)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 10, 251, 21))
        font4 = QFont()
        font4.setPointSize(14)
        font4.setBold(True)
        self.label.setFont(font4)
        self.label.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_4 = QLabel(self.tab)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 40, 161, 20))
        self.label_4.setFont(font2)
        self.label_4.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_6 = QLabel(self.tab)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 210, 111, 20))
        font5 = QFont()
        font5.setPointSize(11)
        self.label_6.setFont(font5)
        self.label_6.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.tb12 = QLineEdit(self.tab)
        self.tb12.setObjectName(u"tb12")
        self.tb12.setGeometry(QRect(140, 190, 271, 41))
        self.tb12.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_7 = QLabel(self.tab)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 260, 111, 20))
        self.label_7.setFont(font5)
        self.label_7.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.tb13 = QLineEdit(self.tab)
        self.tb13.setObjectName(u"tb13")
        self.tb13.setGeometry(QRect(140, 240, 271, 41))
        self.tb13.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_8 = QLabel(self.tab)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 310, 111, 20))
        self.label_8.setFont(font5)
        self.label_8.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.tb14 = QLineEdit(self.tab)
        self.tb14.setObjectName(u"tb14")
        self.tb14.setGeometry(QRect(140, 290, 271, 41))
        self.tb14.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_10 = QLabel(self.tab)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(20, 360, 111, 20))
        self.label_10.setFont(font5)
        self.label_10.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.tb15 = QLineEdit(self.tab)
        self.tb15.setObjectName(u"tb15")
        self.tb15.setGeometry(QRect(140, 340, 271, 41))
        self.tb15.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.tb16 = QLineEdit(self.tab)
        self.tb16.setObjectName(u"tb16")
        self.tb16.setGeometry(QRect(140, 390, 271, 41))
        self.tb16.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_11 = QLabel(self.tab)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(20, 410, 111, 20))
        self.label_11.setFont(font5)
        self.label_11.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.b5 = QPushButton(self.tab)
        self.b5.setObjectName(u"b5")
        self.b5.setGeometry(QRect(140, 500, 271, 41))
        font6 = QFont()
        font6.setPointSize(11)
        font6.setBold(True)
        self.b5.setFont(font6)
        self.b5.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.tb17 = QLineEdit(self.tab)
        self.tb17.setObjectName(u"tb17")
        self.tb17.setGeometry(QRect(140, 440, 271, 41))
        font7 = QFont()
        font7.setPointSize(10)
        self.tb17.setFont(font7)
        self.tb17.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.tb17.setEchoMode(QLineEdit.Password)
        self.tb17.setClearButtonEnabled(True)
        self.label_15 = QLabel(self.tab)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(20, 460, 111, 20))
        self.label_15.setFont(font2)
        self.label_15.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_33 = QLabel(self.tab)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(20, 110, 111, 20))
        self.label_33.setFont(font5)
        self.label_33.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.cb21_4 = QComboBox(self.tab)
        self.cb21_4.addItem("")
        self.cb21_4.addItem("")
        self.cb21_4.addItem("")
        self.cb21_4.setObjectName(u"cb21_4")
        self.cb21_4.setGeometry(QRect(140, 140, 271, 41))
        self.cb21_4.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.label_34 = QLabel(self.tab)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(20, 160, 111, 20))
        self.label_34.setFont(font5)
        self.label_34.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.cb21_5 = QComboBox(self.tab)
        self.cb21_5.addItem("")
        self.cb21_5.addItem("")
        self.cb21_5.setObjectName(u"cb21_5")
        self.cb21_5.setGeometry(QRect(140, 90, 271, 41))
        self.cb21_5.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.label_2 = QLabel(self.tab_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 20, 291, 21))
        self.label_2.setFont(font4)
        self.label_2.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_12 = QLabel(self.tab_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 90, 121, 20))
        self.label_12.setFont(font2)
        self.label_12.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_24 = QLabel(self.tab_2)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(20, 450, 111, 20))
        self.label_24.setFont(font5)
        self.label_24.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_26 = QLabel(self.tab_2)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(20, 300, 111, 20))
        self.label_26.setFont(font5)
        self.label_26.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.tb22 = QLineEdit(self.tab_2)
        self.tb22.setObjectName(u"tb22")
        self.tb22.setGeometry(QRect(140, 230, 271, 41))
        self.tb22.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_28 = QLabel(self.tab_2)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(20, 350, 111, 20))
        self.label_28.setFont(font5)
        self.label_28.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.tb24 = QLineEdit(self.tab_2)
        self.tb24.setObjectName(u"tb24")
        self.tb24.setGeometry(QRect(140, 330, 271, 41))
        self.tb24.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.tb25 = QLineEdit(self.tab_2)
        self.tb25.setObjectName(u"tb25")
        self.tb25.setGeometry(QRect(140, 380, 271, 41))
        self.tb25.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_29 = QLabel(self.tab_2)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(20, 400, 111, 20))
        self.label_29.setFont(font5)
        self.label_29.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.tb26 = QLineEdit(self.tab_2)
        self.tb26.setObjectName(u"tb26")
        self.tb26.setGeometry(QRect(140, 430, 271, 41))
        self.tb26.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_30 = QLabel(self.tab_2)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(20, 250, 111, 20))
        self.label_30.setFont(font5)
        self.label_30.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.b6 = QPushButton(self.tab_2)
        self.b6.setObjectName(u"b6")
        self.b6.setGeometry(QRect(20, 580, 181, 41))
        self.b6.setFont(font6)
        self.b6.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.tb23 = QLineEdit(self.tab_2)
        self.tb23.setObjectName(u"tb23")
        self.tb23.setGeometry(QRect(140, 280, 271, 41))
        self.tb23.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.cb21 = QComboBox(self.tab_2)
        self.cb21.setObjectName(u"cb21")
        self.cb21.setGeometry(QRect(140, 70, 271, 41))
        self.cb21.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.b7 = QPushButton(self.tab_2)
        self.b7.setObjectName(u"b7")
        self.b7.setGeometry(QRect(220, 580, 191, 41))
        self.b7.setFont(font6)
        self.b7.setStyleSheet(u"background-color: rgb(255, 85, 0);")
        self.tb27 = QLineEdit(self.tab_2)
        self.tb27.setObjectName(u"tb27")
        self.tb27.setGeometry(QRect(140, 480, 271, 41))
        self.tb27.setFont(font7)
        self.tb27.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.tb27.setEchoMode(QLineEdit.Password)
        self.tb27.setClearButtonEnabled(True)
        self.label_16 = QLabel(self.tab_2)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(10, 500, 111, 20))
        self.label_16.setFont(font2)
        self.label_16.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_31 = QLabel(self.tab_2)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(20, 200, 111, 20))
        self.label_31.setFont(font5)
        self.label_31.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.cb21_2 = QComboBox(self.tab_2)
        self.cb21_2.addItem("")
        self.cb21_2.addItem("")
        self.cb21_2.addItem("")
        self.cb21_2.setObjectName(u"cb21_2")
        self.cb21_2.setGeometry(QRect(140, 180, 271, 41))
        self.cb21_2.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.cb21_3 = QComboBox(self.tab_2)
        self.cb21_3.addItem("")
        self.cb21_3.addItem("")
        self.cb21_3.setObjectName(u"cb21_3")
        self.cb21_3.setGeometry(QRect(140, 130, 271, 41))
        self.cb21_3.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.label_32 = QLabel(self.tab_2)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(20, 150, 111, 20))
        self.label_32.setFont(font5)
        self.label_32.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.tableWidget_2 = QTableWidget(self.tab_2)
        self.tableWidget_2.setObjectName(u"tableWidget_2")
        self.tableWidget_2.setGeometry(QRect(480, 70, 711, 451))
        self.tableWidget_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.cb21_6 = QComboBox(self.tab_2)
        self.cb21_6.addItem("")
        self.cb21_6.addItem("")
        self.cb21_6.addItem("")
        self.cb21_6.setObjectName(u"cb21_6")
        self.cb21_6.setGeometry(QRect(700, 20, 271, 41))
        self.cb21_6.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.label_63 = QLabel(self.tab_2)
        self.label_63.setObjectName(u"label_63")
        self.label_63.setGeometry(QRect(590, 30, 101, 20))
        self.label_63.setFont(font2)
        self.label_63.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.lessonTable = QTableWidget(self.tab_6)
        if (self.lessonTable.columnCount() < 5):
            self.lessonTable.setColumnCount(5)
        __qtablewidgetitem = QTableWidgetItem()
        self.lessonTable.setHorizontalHeaderItem(0, __qtablewidgetitem)
        font8 = QFont()
        font8.setPointSize(12)
        font8.setBold(True)
        __qtablewidgetitem1 = QTableWidgetItem()
        __qtablewidgetitem1.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        __qtablewidgetitem1.setFont(font8);
        self.lessonTable.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        __qtablewidgetitem2.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        __qtablewidgetitem2.setFont(font8);
        self.lessonTable.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        __qtablewidgetitem3.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        __qtablewidgetitem3.setFont(font8);
        self.lessonTable.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        __qtablewidgetitem4.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        __qtablewidgetitem4.setFont(font8);
        self.lessonTable.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        self.lessonTable.setObjectName(u"lessonTable")
        self.lessonTable.setGeometry(QRect(50, 200, 1095, 421))
        font9 = QFont()
        font9.setPointSize(12)
        font9.setBold(False)
        self.lessonTable.setFont(font9)
        self.lessonTable.setMouseTracking(False)
        self.lessonTable.setTabletTracking(False)
        self.lessonTable.setToolTipDuration(-1)
        self.lessonTable.setAutoFillBackground(False)
        self.lessonTable.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lessonTable.setSortingEnabled(False)
        self.lessonTable.horizontalHeader().setCascadingSectionResizes(False)
        self.lessonTable.horizontalHeader().setDefaultSectionSize(218)
        self.label_5 = QLabel(self.tab_6)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(50, 10, 231, 31))
        font10 = QFont()
        font10.setPointSize(17)
        font10.setBold(True)
        font10.setUnderline(True)
        self.label_5.setFont(font10)
        self.label_5.setToolTipDuration(-1)
        self.label_5.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_5.setIndent(0)
        self.deleteAllLessonsBtn = QPushButton(self.tab_6)
        self.deleteAllLessonsBtn.setObjectName(u"deleteAllLessonsBtn")
        self.deleteAllLessonsBtn.setGeometry(QRect(980, 630, 161, 41))
        self.deleteAllLessonsBtn.setFont(font6)
        self.deleteAllLessonsBtn.setToolTipDuration(-1)
        self.deleteAllLessonsBtn.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.lessonName = QLineEdit(self.tab_6)
        self.lessonName.setObjectName(u"lessonName")
        self.lessonName.setGeometry(QRect(680, 50, 461, 41))
        font11 = QFont()
        font11.setFamilies([u"MS Shell Dlg 2"])
        font11.setPointSize(12)
        font11.setBold(False)
        font11.setItalic(False)
        font11.setUnderline(True)
        self.lessonName.setFont(font11)
        self.lessonName.setToolTipDuration(-1)
        self.lessonName.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.timeSlot = QLineEdit(self.tab_6)
        self.timeSlot.setObjectName(u"timeSlot")
        self.timeSlot.setGeometry(QRect(680, 100, 461, 41))
        self.timeSlot.setToolTipDuration(-1)
        self.timeSlot.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.deleteLessonBtn = QPushButton(self.tab_6)
        self.deleteLessonBtn.setObjectName(u"deleteLessonBtn")
        self.deleteLessonBtn.setGeometry(QRect(50, 630, 141, 41))
        self.deleteLessonBtn.setFont(font6)
        self.deleteLessonBtn.setToolTipDuration(-1)
        self.deleteLessonBtn.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.comboBox_instructor = QComboBox(self.tab_6)
        self.comboBox_instructor.setObjectName(u"comboBox_instructor")
        self.comboBox_instructor.setGeometry(QRect(210, 100, 311, 41))
        font12 = QFont()
        font12.setPointSize(12)
        self.comboBox_instructor.setFont(font12)
        self.comboBox_instructor.setToolTipDuration(0)
        self.comboBox_instructor.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.comboBox_instructor.setMaxVisibleItems(30)
        self.comboBox_instructor.setMinimumContentsLength(6)
        self.label_9 = QLabel(self.tab_6)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(90, 60, 111, 21))
        font13 = QFont()
        font13.setPointSize(11)
        font13.setBold(True)
        font13.setUnderline(False)
        font13.setKerning(True)
        self.label_9.setFont(font13)
        self.label_9.setToolTipDuration(-1)
        self.label_9.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_9.setIndent(0)
        self.resetLessonBtn = QPushButton(self.tab_6)
        self.resetLessonBtn.setObjectName(u"resetLessonBtn")
        self.resetLessonBtn.setGeometry(QRect(830, 150, 151, 41))
        self.resetLessonBtn.setFont(font6)
        self.resetLessonBtn.setToolTipDuration(-1)
        self.resetLessonBtn.setStyleSheet(u"background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255)")
        self.label_21 = QLabel(self.tab_6)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(550, 60, 121, 21))
        self.label_21.setFont(font13)
        self.label_21.setToolTipDuration(-1)
        self.label_21.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_21.setIndent(0)
        self.label_22 = QLabel(self.tab_6)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(50, 170, 231, 21))
        self.label_22.setFont(font10)
        self.label_22.setToolTipDuration(-1)
        self.label_22.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_22.setIndent(0)
        self.dateInput = QLineEdit(self.tab_6)
        self.dateInput.setObjectName(u"dateInput")
        self.dateInput.setGeometry(QRect(210, 50, 311, 41))
        self.dateInput.setToolTipDuration(-1)
        self.dateInput.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.label_23 = QLabel(self.tab_6)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(530, 110, 141, 21))
        self.label_23.setFont(font13)
        self.label_23.setToolTipDuration(-1)
        self.label_23.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_23.setIndent(0)
        self.addLessonBtn = QPushButton(self.tab_6)
        self.addLessonBtn.setObjectName(u"addLessonBtn")
        self.addLessonBtn.setGeometry(QRect(990, 150, 151, 41))
        self.addLessonBtn.setFont(font6)
        self.addLessonBtn.setToolTipDuration(-1)
        self.addLessonBtn.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.label_25 = QLabel(self.tab_6)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(50, 110, 151, 21))
        self.label_25.setFont(font13)
        self.label_25.setToolTipDuration(-1)
        self.label_25.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_25.setIndent(0)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QWidget()
        self.tab_7.setObjectName(u"tab_7")
        self.markAttendanceBtn = QPushButton(self.tab_7)
        self.markAttendanceBtn.setObjectName(u"markAttendanceBtn")
        self.markAttendanceBtn.setGeometry(QRect(1000, 110, 131, 41))
        self.markAttendanceBtn.setFont(font8)
        self.markAttendanceBtn.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.deleteAttendanceBtn = QPushButton(self.tab_7)
        self.deleteAttendanceBtn.setObjectName(u"deleteAttendanceBtn")
        self.deleteAttendanceBtn.setGeometry(QRect(40, 640, 201, 41))
        self.deleteAttendanceBtn.setFont(font6)
        self.deleteAttendanceBtn.setToolTipDuration(-1)
        self.deleteAttendanceBtn.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.recordsList = QListWidget(self.tab_7)
        self.recordsList.setObjectName(u"recordsList")
        self.recordsList.setGeometry(QRect(40, 230, 1091, 401))
        self.recordsList.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_111 = QLabel(self.tab_7)
        self.label_111.setObjectName(u"label_111")
        self.label_111.setGeometry(QRect(40, 200, 181, 21))
        self.label_111.setFont(font8)
        self.label_111.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_57 = QLabel(self.tab_7)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setGeometry(QRect(40, 10, 481, 31))
        self.label_57.setFont(font10)
        self.label_57.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_109 = QLabel(self.tab_7)
        self.label_109.setObjectName(u"label_109")
        self.label_109.setGeometry(QRect(40, 60, 121, 21))
        self.label_109.setFont(font8)
        self.label_109.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.statusComboBox = QComboBox(self.tab_7)
        self.statusComboBox.addItem("")
        self.statusComboBox.addItem("")
        self.statusComboBox.addItem("")
        self.statusComboBox.setObjectName(u"statusComboBox")
        self.statusComboBox.setGeometry(QRect(790, 110, 171, 41))
        self.statusComboBox.setFont(font12)
        self.statusComboBox.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.studentComboBox = QComboBox(self.tab_7)
        self.studentComboBox.setObjectName(u"studentComboBox")
        self.studentComboBox.setGeometry(QRect(170, 50, 351, 41))
        self.studentComboBox.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.deleteSelectedStudentAttendanceBtn = QPushButton(self.tab_7)
        self.deleteSelectedStudentAttendanceBtn.setObjectName(u"deleteSelectedStudentAttendanceBtn")
        self.deleteSelectedStudentAttendanceBtn.setGeometry(QRect(310, 640, 341, 41))
        self.deleteSelectedStudentAttendanceBtn.setFont(font6)
        self.deleteSelectedStudentAttendanceBtn.setToolTipDuration(-1)
        self.deleteSelectedStudentAttendanceBtn.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.deleteAllAttendanceBtn = QPushButton(self.tab_7)
        self.deleteAllAttendanceBtn.setObjectName(u"deleteAllAttendanceBtn")
        self.deleteAllAttendanceBtn.setGeometry(QRect(970, 640, 161, 41))
        self.deleteAllAttendanceBtn.setFont(font6)
        self.deleteAllAttendanceBtn.setToolTipDuration(-1)
        self.deleteAllAttendanceBtn.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.lessonComboBox = QComboBox(self.tab_7)
        self.lessonComboBox.setObjectName(u"lessonComboBox")
        self.lessonComboBox.setGeometry(QRect(170, 110, 581, 41))
        self.lessonComboBox.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_103 = QLabel(self.tab_7)
        self.label_103.setObjectName(u"label_103")
        self.label_103.setGeometry(QRect(40, 120, 121, 21))
        self.label_103.setFont(font8)
        self.label_103.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_110 = QLabel(self.tab_7)
        self.label_110.setObjectName(u"label_110")
        self.label_110.setGeometry(QRect(790, 80, 161, 21))
        self.label_110.setFont(font8)
        self.label_110.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QWidget()
        self.tab_8.setObjectName(u"tab_8")
        self.meetingTable = QTableWidget(self.tab_8)
        if (self.meetingTable.columnCount() < 3):
            self.meetingTable.setColumnCount(3)
        __qtablewidgetitem5 = QTableWidgetItem()
        __qtablewidgetitem5.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        __qtablewidgetitem5.setFont(font8);
        self.meetingTable.setHorizontalHeaderItem(0, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        __qtablewidgetitem6.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        __qtablewidgetitem6.setFont(font8);
        self.meetingTable.setHorizontalHeaderItem(1, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        __qtablewidgetitem7.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        __qtablewidgetitem7.setFont(font8);
        self.meetingTable.setHorizontalHeaderItem(2, __qtablewidgetitem7)
        self.meetingTable.setObjectName(u"meetingTable")
        self.meetingTable.setGeometry(QRect(420, 100, 721, 521))
        self.meetingTable.setFont(font9)
        self.meetingTable.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.meetingTable.horizontalHeader().setDefaultSectionSize(239)
        self.label_27 = QLabel(self.tab_8)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(420, 30, 231, 31))
        self.label_27.setFont(font10)
        self.label_27.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.resetMeetingBtn = QPushButton(self.tab_8)
        self.resetMeetingBtn.setObjectName(u"resetMeetingBtn")
        self.resetMeetingBtn.setGeometry(QRect(70, 340, 151, 41))
        self.resetMeetingBtn.setFont(font6)
        self.resetMeetingBtn.setToolTipDuration(-1)
        self.resetMeetingBtn.setStyleSheet(u"background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255)")
        self.deleteMeetingBtn = QPushButton(self.tab_8)
        self.deleteMeetingBtn.setObjectName(u"deleteMeetingBtn")
        self.deleteMeetingBtn.setGeometry(QRect(420, 630, 141, 41))
        self.deleteMeetingBtn.setFont(font6)
        self.deleteMeetingBtn.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.deleteAllMeetingsBtn = QPushButton(self.tab_8)
        self.deleteAllMeetingsBtn.setObjectName(u"deleteAllMeetingsBtn")
        self.deleteAllMeetingsBtn.setGeometry(QRect(980, 630, 161, 41))
        self.deleteAllMeetingsBtn.setFont(font6)
        self.deleteAllMeetingsBtn.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.label_35 = QLabel(self.tab_8)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(60, 30, 241, 31))
        self.label_35.setFont(font10)
        self.label_35.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.meetingTitle = QLineEdit(self.tab_8)
        self.meetingTitle.setObjectName(u"meetingTitle")
        self.meetingTitle.setGeometry(QRect(70, 190, 311, 41))
        self.meetingTitle.setFont(font11)
        self.meetingTitle.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.label_36 = QLabel(self.tab_8)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(60, 160, 111, 21))
        font14 = QFont()
        font14.setPointSize(11)
        font14.setBold(True)
        font14.setUnderline(True)
        font14.setKerning(True)
        self.label_36.setFont(font14)
        self.label_36.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.meetingTimeSlot = QLineEdit(self.tab_8)
        self.meetingTimeSlot.setObjectName(u"meetingTimeSlot")
        self.meetingTimeSlot.setGeometry(QRect(70, 280, 311, 41))
        self.meetingTimeSlot.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.label_37 = QLabel(self.tab_8)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(60, 70, 111, 21))
        self.label_37.setFont(font14)
        self.label_37.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.meetingDateInput = QLineEdit(self.tab_8)
        self.meetingDateInput.setObjectName(u"meetingDateInput")
        self.meetingDateInput.setGeometry(QRect(70, 100, 311, 41))
        self.meetingDateInput.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.addMeetingBtn = QPushButton(self.tab_8)
        self.addMeetingBtn.setObjectName(u"addMeetingBtn")
        self.addMeetingBtn.setGeometry(QRect(230, 340, 151, 41))
        self.addMeetingBtn.setFont(font6)
        self.addMeetingBtn.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.label_38 = QLabel(self.tab_8)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(60, 250, 141, 21))
        self.label_38.setFont(font14)
        self.label_38.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.tabWidget.addTab(self.tab_8, "")
        self.tab_9 = QWidget()
        self.tab_9.setObjectName(u"tab_9")
        self.label_123 = QLabel(self.tab_9)
        self.label_123.setObjectName(u"label_123")
        self.label_123.setGeometry(QRect(60, 60, 121, 21))
        self.label_123.setFont(font8)
        self.label_123.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.recordsList_4 = QListWidget(self.tab_9)
        self.recordsList_4.setObjectName(u"recordsList_4")
        self.recordsList_4.setGeometry(QRect(60, 230, 1091, 401))
        self.recordsList_4.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.statusComboBox_4 = QComboBox(self.tab_9)
        self.statusComboBox_4.addItem("")
        self.statusComboBox_4.addItem("")
        self.statusComboBox_4.addItem("")
        self.statusComboBox_4.setObjectName(u"statusComboBox_4")
        self.statusComboBox_4.setGeometry(QRect(810, 110, 171, 41))
        self.statusComboBox_4.setFont(font12)
        self.statusComboBox_4.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_124 = QLabel(self.tab_9)
        self.label_124.setObjectName(u"label_124")
        self.label_124.setGeometry(QRect(810, 80, 161, 21))
        self.label_124.setFont(font8)
        self.label_124.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.studentComboBox_4 = QComboBox(self.tab_9)
        self.studentComboBox_4.setObjectName(u"studentComboBox_4")
        self.studentComboBox_4.setGeometry(QRect(190, 50, 351, 41))
        self.studentComboBox_4.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.deleteAttendanceBtn_4 = QPushButton(self.tab_9)
        self.deleteAttendanceBtn_4.setObjectName(u"deleteAttendanceBtn_4")
        self.deleteAttendanceBtn_4.setGeometry(QRect(60, 640, 201, 41))
        self.deleteAttendanceBtn_4.setFont(font6)
        self.deleteAttendanceBtn_4.setToolTipDuration(-1)
        self.deleteAttendanceBtn_4.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.label_125 = QLabel(self.tab_9)
        self.label_125.setObjectName(u"label_125")
        self.label_125.setGeometry(QRect(60, 10, 461, 31))
        self.label_125.setFont(font10)
        self.label_125.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.meetingComboBox_3 = QComboBox(self.tab_9)
        self.meetingComboBox_3.setObjectName(u"meetingComboBox_3")
        self.meetingComboBox_3.setGeometry(QRect(190, 110, 581, 41))
        self.meetingComboBox_3.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_126 = QLabel(self.tab_9)
        self.label_126.setObjectName(u"label_126")
        self.label_126.setGeometry(QRect(60, 120, 121, 21))
        self.label_126.setFont(font8)
        self.label_126.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.markAttendanceBtn_4 = QPushButton(self.tab_9)
        self.markAttendanceBtn_4.setObjectName(u"markAttendanceBtn_4")
        self.markAttendanceBtn_4.setGeometry(QRect(1020, 110, 131, 41))
        self.markAttendanceBtn_4.setFont(font8)
        self.markAttendanceBtn_4.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.deleteAllAttendanceBtn_4 = QPushButton(self.tab_9)
        self.deleteAllAttendanceBtn_4.setObjectName(u"deleteAllAttendanceBtn_4")
        self.deleteAllAttendanceBtn_4.setGeometry(QRect(990, 640, 161, 41))
        self.deleteAllAttendanceBtn_4.setFont(font6)
        self.deleteAllAttendanceBtn_4.setToolTipDuration(-1)
        self.deleteAllAttendanceBtn_4.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.label_127 = QLabel(self.tab_9)
        self.label_127.setObjectName(u"label_127")
        self.label_127.setGeometry(QRect(60, 200, 241, 21))
        self.label_127.setFont(font8)
        self.label_127.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.deleteSelectedStudentAttendanceBtn_4 = QPushButton(self.tab_9)
        self.deleteSelectedStudentAttendanceBtn_4.setObjectName(u"deleteSelectedStudentAttendanceBtn_4")
        self.deleteSelectedStudentAttendanceBtn_4.setGeometry(QRect(330, 640, 341, 41))
        self.deleteSelectedStudentAttendanceBtn_4.setFont(font6)
        self.deleteSelectedStudentAttendanceBtn_4.setToolTipDuration(-1)
        self.deleteSelectedStudentAttendanceBtn_4.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.tabWidget.addTab(self.tab_9, "")
        self.tab_10 = QWidget()
        self.tab_10.setObjectName(u"tab_10")
        self.announcementCombobox_a = QComboBox(self.tab_10)
        self.announcementCombobox_a.setObjectName(u"announcementCombobox_a")
        self.announcementCombobox_a.setGeometry(QRect(640, 80, 471, 51))
        self.announcementCombobox_a.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.announcementTitle_a = QLineEdit(self.tab_10)
        self.announcementTitle_a.setObjectName(u"announcementTitle_a")
        self.announcementTitle_a.setGeometry(QRect(220, 160, 321, 51))
        font15 = QFont()
        font15.setBold(True)
        font15.setItalic(True)
        self.announcementTitle_a.setFont(font15)
        self.announcementTitle_a.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_68 = QLabel(self.tab_10)
        self.label_68.setObjectName(u"label_68")
        self.label_68.setGeometry(QRect(20, 240, 151, 41))
        self.label_68.setFont(font4)
        self.label_68.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.textEdit_a = QTextEdit(self.tab_10)
        self.textEdit_a.setObjectName(u"textEdit_a")
        self.textEdit_a.setGeometry(QRect(220, 240, 321, 271))
        self.textEdit_a.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.textEdit_a.setInputMethodHints(Qt.ImhMultiLine)
        self.label_66 = QLabel(self.tab_10)
        self.label_66.setObjectName(u"label_66")
        self.label_66.setGeometry(QRect(20, 100, 181, 31))
        self.label_66.setFont(font4)
        self.label_66.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.addButton_a = QPushButton(self.tab_10)
        self.addButton_a.setObjectName(u"addButton_a")
        self.addButton_a.setGeometry(QRect(220, 530, 91, 51))
        self.addButton_a.setFont(font6)
        self.addButton_a.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.deleteButton_a = QPushButton(self.tab_10)
        self.deleteButton_a.setObjectName(u"deleteButton_a")
        self.deleteButton_a.setGeometry(QRect(450, 530, 91, 51))
        self.deleteButton_a.setFont(font6)
        self.deleteButton_a.setStyleSheet(u"background-color: rgb(170, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.editButton_a = QPushButton(self.tab_10)
        self.editButton_a.setObjectName(u"editButton_a")
        self.editButton_a.setGeometry(QRect(330, 530, 101, 51))
        self.editButton_a.setFont(font6)
        self.editButton_a.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.label_67 = QLabel(self.tab_10)
        self.label_67.setObjectName(u"label_67")
        self.label_67.setGeometry(QRect(20, 170, 151, 31))
        self.label_67.setFont(font4)
        self.label_67.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_65 = QLabel(self.tab_10)
        self.label_65.setObjectName(u"label_65")
        self.label_65.setGeometry(QRect(640, 180, 211, 21))
        self.label_65.setFont(font4)
        self.label_65.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_58 = QLabel(self.tab_10)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setGeometry(QRect(20, 40, 531, 41))
        font16 = QFont()
        font16.setPointSize(18)
        font16.setBold(True)
        self.label_58.setFont(font16)
        self.label_58.setStyleSheet(u"color: rgb(255, 191, 16);\n"
"fontSize: 20px")
        self.announcementListView_a = QListView(self.tab_10)
        self.announcementListView_a.setObjectName(u"announcementListView_a")
        self.announcementListView_a.setGeometry(QRect(640, 220, 471, 421))
        self.announcementListView_a.setStyleSheet(u"background: rgb(255, 255, 255)")
        self.announcementDate_a = QLineEdit(self.tab_10)
        self.announcementDate_a.setObjectName(u"announcementDate_a")
        self.announcementDate_a.setGeometry(QRect(220, 100, 321, 41))
        self.announcementDate_a.setToolTipDuration(-1)
        self.announcementDate_a.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.label_69 = QLabel(self.tab_10)
        self.label_69.setObjectName(u"label_69")
        self.label_69.setGeometry(QRect(640, 40, 481, 31))
        self.label_69.setFont(font16)
        self.label_69.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.tabWidget.addTab(self.tab_10, "")
        self.tab_11 = QWidget()
        self.tab_11.setObjectName(u"tab_11")
        self.label_42 = QLabel(self.tab_11)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(490, 20, 211, 21))
        font17 = QFont()
        font17.setPointSize(16)
        font17.setBold(True)
        font17.setUnderline(True)
        self.label_42.setFont(font17)
        self.label_42.setToolTipDuration(-1)
        self.label_42.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_42.setIndent(0)
        self.deadlineInput_a = QLineEdit(self.tab_11)
        self.deadlineInput_a.setObjectName(u"deadlineInput_a")
        self.deadlineInput_a.setGeometry(QRect(540, 70, 411, 41))
        self.deadlineInput_a.setToolTipDuration(-1)
        self.deadlineInput_a.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.resAllTodoFields_a = QPushButton(self.tab_11)
        self.resAllTodoFields_a.setObjectName(u"resAllTodoFields_a")
        self.resAllTodoFields_a.setGeometry(QRect(960, 70, 161, 41))
        self.resAllTodoFields_a.setFont(font6)
        self.resAllTodoFields_a.setToolTipDuration(-1)
        self.resAllTodoFields_a.setStyleSheet(u"background-color: rgb(255, 191, 16);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 0, 0);")
        self.deleteTodoBtn_a = QPushButton(self.tab_11)
        self.deleteTodoBtn_a.setObjectName(u"deleteTodoBtn_a")
        self.deleteTodoBtn_a.setGeometry(QRect(90, 610, 141, 41))
        self.deleteTodoBtn_a.setFont(font6)
        self.deleteTodoBtn_a.setToolTipDuration(-1)
        self.deleteTodoBtn_a.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.label_43 = QLabel(self.tab_11)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(80, 150, 101, 21))
        font18 = QFont()
        font18.setPointSize(12)
        font18.setBold(True)
        font18.setUnderline(True)
        self.label_43.setFont(font18)
        self.label_43.setToolTipDuration(-1)
        self.label_43.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_43.setIndent(0)
        self.label_44 = QLabel(self.tab_11)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(90, 80, 71, 21))
        font19 = QFont()
        font19.setPointSize(14)
        font19.setBold(True)
        font19.setUnderline(True)
        self.label_44.setFont(font19)
        self.label_44.setToolTipDuration(-1)
        self.label_44.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_44.setIndent(0)
        self.todoName_a = QLineEdit(self.tab_11)
        self.todoName_a.setObjectName(u"todoName_a")
        self.todoName_a.setGeometry(QRect(190, 140, 761, 41))
        self.todoName_a.setFont(font11)
        self.todoName_a.setToolTipDuration(-1)
        self.todoName_a.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.todoName_a.setAlignment(Qt.AlignCenter)
        self.comboBox_student_a = QComboBox(self.tab_11)
        self.comboBox_student_a.setObjectName(u"comboBox_student_a")
        self.comboBox_student_a.setGeometry(QRect(190, 70, 231, 41))
        self.comboBox_student_a.setFont(font12)
        self.comboBox_student_a.setToolTipDuration(0)
        self.comboBox_student_a.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.comboBox_student_a.setMaxVisibleItems(30)
        self.comboBox_student_a.setMinimumContentsLength(6)
        self.allTodosBtn_a = QPushButton(self.tab_11)
        self.allTodosBtn_a.setObjectName(u"allTodosBtn_a")
        self.allTodosBtn_a.setGeometry(QRect(420, 70, 111, 41))
        self.allTodosBtn_a.setFont(font6)
        self.allTodosBtn_a.setToolTipDuration(-1)
        self.allTodosBtn_a.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.addTodoBtn_a = QPushButton(self.tab_11)
        self.addTodoBtn_a.setObjectName(u"addTodoBtn_a")
        self.addTodoBtn_a.setGeometry(QRect(960, 120, 161, 61))
        self.addTodoBtn_a.setFont(font6)
        self.addTodoBtn_a.setToolTipDuration(-1)
        self.addTodoBtn_a.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.deleteAllTodosBtn_a = QPushButton(self.tab_11)
        self.deleteAllTodosBtn_a.setObjectName(u"deleteAllTodosBtn_a")
        self.deleteAllTodosBtn_a.setGeometry(QRect(960, 610, 161, 41))
        self.deleteAllTodosBtn_a.setFont(font6)
        self.deleteAllTodosBtn_a.setToolTipDuration(-1)
        self.deleteAllTodosBtn_a.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.todoTable_a = QTableWidget(self.tab_11)
        if (self.todoTable_a.columnCount() < 7):
            self.todoTable_a.setColumnCount(7)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.todoTable_a.setHorizontalHeaderItem(0, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        __qtablewidgetitem9.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        __qtablewidgetitem9.setFont(font8);
        self.todoTable_a.setHorizontalHeaderItem(1, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        __qtablewidgetitem10.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        __qtablewidgetitem10.setFont(font8);
        self.todoTable_a.setHorizontalHeaderItem(2, __qtablewidgetitem10)
        __qtablewidgetitem11 = QTableWidgetItem()
        __qtablewidgetitem11.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        __qtablewidgetitem11.setFont(font8);
        self.todoTable_a.setHorizontalHeaderItem(3, __qtablewidgetitem11)
        __qtablewidgetitem12 = QTableWidgetItem()
        __qtablewidgetitem12.setFont(font8);
        self.todoTable_a.setHorizontalHeaderItem(4, __qtablewidgetitem12)
        __qtablewidgetitem13 = QTableWidgetItem()
        __qtablewidgetitem13.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        __qtablewidgetitem13.setFont(font8);
        self.todoTable_a.setHorizontalHeaderItem(5, __qtablewidgetitem13)
        __qtablewidgetitem14 = QTableWidgetItem()
        self.todoTable_a.setHorizontalHeaderItem(6, __qtablewidgetitem14)
        self.todoTable_a.setObjectName(u"todoTable_a")
        self.todoTable_a.setGeometry(QRect(90, 200, 1031, 401))
        self.todoTable_a.setFont(font9)
        self.todoTable_a.setMouseTracking(False)
        self.todoTable_a.setTabletTracking(False)
        self.todoTable_a.setToolTipDuration(-1)
        self.todoTable_a.setAutoFillBackground(False)
        self.todoTable_a.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.todoTable_a.setSortingEnabled(False)
        self.todoTable_a.horizontalHeader().setCascadingSectionResizes(False)
        self.todoTable_a.horizontalHeader().setDefaultSectionSize(218)
        self.tabWidget.addTab(self.tab_11, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.sendMessage = QPushButton(self.tab_4)
        self.sendMessage.setObjectName(u"sendMessage")
        self.sendMessage.setGeometry(QRect(850, 600, 201, 51))
        self.sendMessage.setFont(font6)
        self.sendMessage.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.listView_chats = QListView(self.tab_4)
        self.listView_chats.setObjectName(u"listView_chats")
        self.listView_chats.setGeometry(QRect(50, 200, 401, 381))
        self.listView_chats.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.typeMessage = QLineEdit(self.tab_4)
        self.typeMessage.setObjectName(u"typeMessage")
        self.typeMessage.setGeometry(QRect(550, 510, 501, 71))
        self.typeMessage.setFont(font15)
        self.typeMessage.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_105 = QLabel(self.tab_4)
        self.label_105.setObjectName(u"label_105")
        self.label_105.setGeometry(QRect(50, 50, 281, 21))
        self.label_105.setFont(font8)
        self.label_105.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.messageCombobox = QComboBox(self.tab_4)
        self.messageCombobox.setObjectName(u"messageCombobox")
        self.messageCombobox.setGeometry(QRect(50, 90, 401, 41))
        self.messageCombobox.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_107 = QLabel(self.tab_4)
        self.label_107.setObjectName(u"label_107")
        self.label_107.setGeometry(QRect(50, 160, 281, 21))
        self.label_107.setFont(font8)
        self.label_107.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_115 = QLabel(self.tab_4)
        self.label_115.setObjectName(u"label_115")
        self.label_115.setGeometry(QRect(550, 40, 461, 31))
        font20 = QFont()
        font20.setPointSize(16)
        font20.setBold(True)
        self.label_115.setFont(font20)
        self.label_115.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.username = QLabel(self.tab_4)
        self.username.setObjectName(u"username")
        self.username.setGeometry(QRect(550, 90, 281, 21))
        self.username.setFont(font16)
        self.username.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.usermail = QLabel(self.tab_4)
        self.usermail.setObjectName(u"usermail")
        self.usermail.setGeometry(QRect(840, 90, 201, 21))
        self.usermail.setFont(font9)
        self.usermail.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.usermail.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.listViewMessages = QListView(self.tab_4)
        self.listViewMessages.setObjectName(u"listViewMessages")
        self.listViewMessages.setGeometry(QRect(550, 130, 501, 361))
        self.listViewMessages.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.dateEdit = QDateEdit(self.tab_5)
        self.dateEdit.setObjectName(u"dateEdit")
        self.dateEdit.setGeometry(QRect(130, 50, 111, 41))
        self.dateEdit.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.dateEdit_2 = QDateEdit(self.tab_5)
        self.dateEdit_2.setObjectName(u"dateEdit_2")
        self.dateEdit_2.setGeometry(QRect(260, 50, 111, 41))
        self.dateEdit_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_17 = QLabel(self.tab_5)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(20, 70, 101, 20))
        self.label_17.setFont(font2)
        self.label_17.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_18 = QLabel(self.tab_5)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(130, 30, 41, 20))
        self.label_18.setFont(font2)
        self.label_18.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_19 = QLabel(self.tab_5)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(260, 30, 41, 20))
        self.label_19.setFont(font2)
        self.label_19.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_20 = QLabel(self.tab_5)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(20, 130, 101, 20))
        self.label_20.setFont(font2)
        self.label_20.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.comboBox = QComboBox(self.tab_5)
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(130, 110, 241, 41))
        self.comboBox.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.b6_2 = QPushButton(self.tab_5)
        self.b6_2.setObjectName(u"b6_2")
        self.b6_2.setGeometry(QRect(850, 110, 141, 41))
        self.b6_2.setFont(font6)
        self.b6_2.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.b6_3 = QPushButton(self.tab_5)
        self.b6_3.setObjectName(u"b6_3")
        self.b6_3.setGeometry(QRect(1050, 110, 141, 41))
        self.b6_3.setFont(font6)
        self.b6_3.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.tableWidget = QTableWidget(self.tab_5)
        if (self.tableWidget.columnCount() < 5):
            self.tableWidget.setColumnCount(5)
        __qtablewidgetitem15 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem15)
        __qtablewidgetitem16 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, __qtablewidgetitem16)
        __qtablewidgetitem17 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, __qtablewidgetitem17)
        __qtablewidgetitem18 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, __qtablewidgetitem18)
        __qtablewidgetitem19 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, __qtablewidgetitem19)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(20, 160, 1171, 531))
        self.tableWidget.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.tableWidget.horizontalHeader().setDefaultSectionSize(236)
        self.comboBox_2 = QComboBox(self.tab_5)
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(530, 110, 241, 41))
        self.comboBox_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_62 = QLabel(self.tab_5)
        self.label_62.setObjectName(u"label_62")
        self.label_62.setGeometry(QRect(470, 130, 51, 20))
        self.label_62.setFont(font2)
        self.label_62.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.tabWidget.addTab(self.tab_5, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1210, 30))
        self.menubar.setStyleSheet(u"background-color: rgb(16, 16, 16);\n"
"color: rgb(255, 191, 16);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.menuTeacher = QMenu(self.menubar)
        self.menuTeacher.setObjectName(u"menuTeacher")
        self.menuMessage_Box = QMenu(self.menubar)
        self.menuMessage_Box.setObjectName(u"menuMessage_Box")
        self.menuExit = QMenu(self.menubar)
        self.menuExit.setObjectName(u"menuExit")
        self.menuReporting = QMenu(self.menubar)
        self.menuReporting.setObjectName(u"menuReporting")
        self.menuTeacher_Functions = QMenu(self.menubar)
        self.menuTeacher_Functions.setObjectName(u"menuTeacher_Functions")
        self.menuMeetings = QMenu(self.menubar)
        self.menuMeetings.setObjectName(u"menuMeetings")
        self.menuTo_Do_List = QMenu(self.menubar)
        self.menuTo_Do_List.setObjectName(u"menuTo_Do_List")
        self.menuAnnouncements = QMenu(self.menubar)
        self.menuAnnouncements.setObjectName(u"menuAnnouncements")
        MainWindow.setMenuBar(self.menubar)

        self.menubar.addAction(self.menuTeacher.menuAction())
        self.menubar.addAction(self.menuTeacher_Functions.menuAction())
        self.menubar.addAction(self.menuMeetings.menuAction())
        self.menubar.addAction(self.menuAnnouncements.menuAction())
        self.menubar.addAction(self.menuTo_Do_List.menuAction())
        self.menubar.addAction(self.menuMessage_Box.menuAction())
        self.menubar.addAction(self.menuReporting.menuAction())
        self.menubar.addAction(self.menuExit.menuAction())
        self.menuTeacher.addAction(self.menu11)
        self.menuTeacher.addAction(self.menu12)
        self.menuMessage_Box.addAction(self.menu61_a)
        self.menuExit.addAction(self.menu71)
        self.menuReporting.addAction(self.actionCheck_Reports)
        self.menuTeacher_Functions.addAction(self.actionAccess_All_Functions)
        self.menuTeacher_Functions.addAction(self.actionLesson_Attendance)
        self.menuMeetings.addAction(self.actionMeeting_Schedule)
        self.menuMeetings.addAction(self.actionMeeting_Attendance)
        self.menuTo_Do_List.addAction(self.actionAdd_Edit_To_Do_List)
        self.menuAnnouncements.addAction(self.actionAdd_Edit_Announcement)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(8)
        self.cb21_4.setCurrentIndex(-1)
        self.cb21_5.setCurrentIndex(-1)
        self.cb21_2.setCurrentIndex(-1)
        self.cb21_3.setCurrentIndex(-1)
        self.comboBox_instructor.setCurrentIndex(-1)
        self.comboBox_student_a.setCurrentIndex(-1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.menu11.setText(QCoreApplication.translate("MainWindow", u"Add User", None))
        self.menu12.setText(QCoreApplication.translate("MainWindow", u"Edit User", None))
        self.menu21.setText(QCoreApplication.translate("MainWindow", u"Add student", None))
        self.menu22.setText(QCoreApplication.translate("MainWindow", u"Edit student", None))
        self.menu31.setText(QCoreApplication.translate("MainWindow", u"Add/Edit Courses", None))
        self.menu41.setText(QCoreApplication.translate("MainWindow", u"Add/Edit Meeting", None))
        self.menu42.setText(QCoreApplication.translate("MainWindow", u"Add/Edit Meeting Attandance", None))
        self.menu32.setText(QCoreApplication.translate("MainWindow", u"Add/Edit Course Schedule", None))
        self.menu33.setText(QCoreApplication.translate("MainWindow", u"Add/Edit Course Attandance", None))
        self.menu51.setText(QCoreApplication.translate("MainWindow", u"Add/Edit To Do List", None))
        self.menu61_a.setText(QCoreApplication.translate("MainWindow", u"Add/Edit Message", None))
        self.menu71.setText(QCoreApplication.translate("MainWindow", u"Logout", None))
        self.actionCheck_Reports.setText(QCoreApplication.translate("MainWindow", u"Check Reports", None))
        self.actionAccess_All_Functions.setText(QCoreApplication.translate("MainWindow", u"Lesson Schedule", None))
        self.actionLesson_Attendance.setText(QCoreApplication.translate("MainWindow", u"Lesson Attendance", None))
        self.actionMeeting_Schedule.setText(QCoreApplication.translate("MainWindow", u"Meeting Schedule", None))
        self.actionMeeting_Attendance.setText(QCoreApplication.translate("MainWindow", u"Meeting Attendance", None))
        self.actionAdd_Edit_To_Do_List.setText(QCoreApplication.translate("MainWindow", u"Add/Edit To Do List", None))
        self.actionAdd_Edit_Announcement.setText(QCoreApplication.translate("MainWindow", u"Add/Edit Announcement", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"   \ue736 SMART SCHOOL > School-Learning-Enhancement-System \ue736", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"You login as admin !!!", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"   \ue736 WELCOME TO SMART SCHOOL \ue736", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"Home", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Add New User", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Enter User Details", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Email", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Name", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Surname", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"City", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Phone", None))
        self.b5.setText(QCoreApplication.translate("MainWindow", u"Save User Details", None))
        self.tb17.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Set password for new user", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Set Password", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"Status", None))
        self.cb21_4.setItemText(0, QCoreApplication.translate("MainWindow", u"admin", None))
        self.cb21_4.setItemText(1, QCoreApplication.translate("MainWindow", u"teacher", None))
        self.cb21_4.setItemText(2, QCoreApplication.translate("MainWindow", u"student", None))

        self.label_34.setText(QCoreApplication.translate("MainWindow", u"User Type", None))
        self.cb21_5.setItemText(0, QCoreApplication.translate("MainWindow", u"Active", None))
        self.cb21_5.setItemText(1, QCoreApplication.translate("MainWindow", u"Pending", None))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Add User", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Edit or Delete User", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Select User", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"Phone", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"Name", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"Surname", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"City", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"Email", None))
        self.b6.setText(QCoreApplication.translate("MainWindow", u"Save User Details", None))
        self.b7.setText(QCoreApplication.translate("MainWindow", u"Delete User Details", None))
        self.tb27.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Set password", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Set Password", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"User Type", None))
        self.cb21_2.setItemText(0, QCoreApplication.translate("MainWindow", u"admin", None))
        self.cb21_2.setItemText(1, QCoreApplication.translate("MainWindow", u"teacher", None))
        self.cb21_2.setItemText(2, QCoreApplication.translate("MainWindow", u"student", None))

        self.cb21_3.setItemText(0, QCoreApplication.translate("MainWindow", u"Active", None))
        self.cb21_3.setItemText(1, QCoreApplication.translate("MainWindow", u"Pending", None))

        self.label_32.setText(QCoreApplication.translate("MainWindow", u"Status", None))
        self.cb21_6.setItemText(0, QCoreApplication.translate("MainWindow", u"Pending", None))
        self.cb21_6.setItemText(1, QCoreApplication.translate("MainWindow", u"Active", None))
        self.cb21_6.setItemText(2, QCoreApplication.translate("MainWindow", u"All", None))

        self.label_63.setText(QCoreApplication.translate("MainWindow", u"User Status", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Edit User", None))
        ___qtablewidgetitem = self.lessonTable.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Lesson ID", None));
        ___qtablewidgetitem1 = self.lessonTable.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Lesson", None));
        ___qtablewidgetitem2 = self.lessonTable.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Date", None));
        ___qtablewidgetitem3 = self.lessonTable.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"Time Slot", None));
        ___qtablewidgetitem4 = self.lessonTable.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"Instructor", None));
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Add/Edit Lesson", None))
        self.deleteAllLessonsBtn.setText(QCoreApplication.translate("MainWindow", u"Delete All Lessons", None))
        self.lessonName.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Please add/select a a lesson", None))
        self.timeSlot.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Please enter a time slot; hh:mm-hh:mm", None))
        self.deleteLessonBtn.setText(QCoreApplication.translate("MainWindow", u"Delete Lesson", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Lesson Date >", None))
        self.resetLessonBtn.setText(QCoreApplication.translate("MainWindow", u"Reset Form", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"Lesson Name >", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"Lesson Schedule", None))
        self.dateInput.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Please select a date for the lesson", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"Lesson Time Slot >", None))
        self.addLessonBtn.setText(QCoreApplication.translate("MainWindow", u"Add/Edit Lesson", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"Select Instructor >", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QCoreApplication.translate("MainWindow", u"Lesson Schedule", None))
        self.markAttendanceBtn.setText(QCoreApplication.translate("MainWindow", u"Save/Update", None))
        self.deleteAttendanceBtn.setText(QCoreApplication.translate("MainWindow", u"Delete a selected record", None))
        self.label_111.setText(QCoreApplication.translate("MainWindow", u"Attendance Records", None))
        self.label_57.setText(QCoreApplication.translate("MainWindow", u"Add/Edit Lesson Attandence Details", None))
        self.label_109.setText(QCoreApplication.translate("MainWindow", u"Select Student", None))
        self.statusComboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"Present", None))
        self.statusComboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"Absent", None))
        self.statusComboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"Late", None))

        self.deleteSelectedStudentAttendanceBtn.setText(QCoreApplication.translate("MainWindow", u"Delete all records for the selected student", None))
        self.deleteAllAttendanceBtn.setText(QCoreApplication.translate("MainWindow", u"Delete All Records", None))
        self.label_103.setText(QCoreApplication.translate("MainWindow", u"Select Lesson", None))
        self.label_110.setText(QCoreApplication.translate("MainWindow", u"Mark Attendance", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), QCoreApplication.translate("MainWindow", u"Lesson Attendance", None))
        ___qtablewidgetitem5 = self.meetingTable.horizontalHeaderItem(0)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"Meeting Title", None));
        ___qtablewidgetitem6 = self.meetingTable.horizontalHeaderItem(1)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("MainWindow", u"Meeting Date", None));
        ___qtablewidgetitem7 = self.meetingTable.horizontalHeaderItem(2)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("MainWindow", u"Meeting Time", None));
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"Meeting Schedule", None))
        self.resetMeetingBtn.setText(QCoreApplication.translate("MainWindow", u"Reset Form", None))
        self.deleteMeetingBtn.setText(QCoreApplication.translate("MainWindow", u"Delete Meeting", None))
        self.deleteAllMeetingsBtn.setText(QCoreApplication.translate("MainWindow", u"Delete All Meetings", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"Add/Edit a meeting", None))
        self.meetingTitle.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Please add a meeting", None))
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"Meeting Title;", None))
        self.meetingTimeSlot.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Please enter a time slot; hh:mm-hh:mm", None))
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"Meeting Date;", None))
        self.meetingDateInput.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Please select a date for a meeting", None))
        self.addMeetingBtn.setText(QCoreApplication.translate("MainWindow", u"Add/Edit Meeting", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"Meeting Time Slot;", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), QCoreApplication.translate("MainWindow", u"Meeting Schedule", None))
        self.label_123.setText(QCoreApplication.translate("MainWindow", u"Select Student", None))
        self.statusComboBox_4.setItemText(0, QCoreApplication.translate("MainWindow", u"Present", None))
        self.statusComboBox_4.setItemText(1, QCoreApplication.translate("MainWindow", u"Absent", None))
        self.statusComboBox_4.setItemText(2, QCoreApplication.translate("MainWindow", u"Late", None))

        self.label_124.setText(QCoreApplication.translate("MainWindow", u"Mark Attendance", None))
        self.deleteAttendanceBtn_4.setText(QCoreApplication.translate("MainWindow", u"Delete a selected record", None))
        self.label_125.setText(QCoreApplication.translate("MainWindow", u"Add/Edit Meeting Attandence Details", None))
        self.label_126.setText(QCoreApplication.translate("MainWindow", u"Select Meeting", None))
        self.markAttendanceBtn_4.setText(QCoreApplication.translate("MainWindow", u"Save/Update", None))
        self.deleteAllAttendanceBtn_4.setText(QCoreApplication.translate("MainWindow", u"Delete All Records", None))
        self.label_127.setText(QCoreApplication.translate("MainWindow", u"Meeting Attendance Records", None))
        self.deleteSelectedStudentAttendanceBtn_4.setText(QCoreApplication.translate("MainWindow", u"Delete all records for the selected student", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), QCoreApplication.translate("MainWindow", u"Meeting Attendance", None))
        self.announcementTitle_a.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Please Type a Title", None))
        self.label_68.setText(QCoreApplication.translate("MainWindow", u"Announcement", None))
        self.textEdit_a.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.label_66.setText(QCoreApplication.translate("MainWindow", u"Select Deadline", None))
        self.addButton_a.setText(QCoreApplication.translate("MainWindow", u"Add", None))
        self.deleteButton_a.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
        self.editButton_a.setText(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.label_67.setText(QCoreApplication.translate("MainWindow", u"Header", None))
        self.label_65.setText(QCoreApplication.translate("MainWindow", u"Announcements", None))
        self.label_58.setText(QCoreApplication.translate("MainWindow", u"Add/Edit  Announcement Details", None))
        self.announcementDate_a.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Please select a date for announcement", None))
        self.label_69.setText(QCoreApplication.translate("MainWindow", u"Select Announcement for Edit", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_10), QCoreApplication.translate("MainWindow", u"Announcement", None))
        self.label_42.setText(QCoreApplication.translate("MainWindow", u"Add/Edit Task", None))
        self.deadlineInput_a.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Please select a deadline", None))
        self.resAllTodoFields_a.setText(QCoreApplication.translate("MainWindow", u"Reset All Fields", None))
        self.deleteTodoBtn_a.setText(QCoreApplication.translate("MainWindow", u"Delete Task", None))
        self.label_43.setText(QCoreApplication.translate("MainWindow", u"Add Task", None))
        self.label_44.setText(QCoreApplication.translate("MainWindow", u"To :", None))
        self.todoName_a.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Type Here", None))
        self.allTodosBtn_a.setText(QCoreApplication.translate("MainWindow", u"All", None))
        self.addTodoBtn_a.setText(QCoreApplication.translate("MainWindow", u"Save / Update", None))
        self.deleteAllTodosBtn_a.setText(QCoreApplication.translate("MainWindow", u"Delete All Tasks", None))
        ___qtablewidgetitem8 = self.todoTable_a.horizontalHeaderItem(0)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("MainWindow", u"Task ID", None));
        ___qtablewidgetitem9 = self.todoTable_a.horizontalHeaderItem(1)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("MainWindow", u"Task", None));
        ___qtablewidgetitem10 = self.todoTable_a.horizontalHeaderItem(2)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("MainWindow", u"Deadline", None));
        ___qtablewidgetitem11 = self.todoTable_a.horizontalHeaderItem(3)
        ___qtablewidgetitem11.setText(QCoreApplication.translate("MainWindow", u"Status", None));
        ___qtablewidgetitem12 = self.todoTable_a.horizontalHeaderItem(4)
        ___qtablewidgetitem12.setText(QCoreApplication.translate("MainWindow", u"Created By", None));
        ___qtablewidgetitem13 = self.todoTable_a.horizontalHeaderItem(5)
        ___qtablewidgetitem13.setText(QCoreApplication.translate("MainWindow", u"Student", None));
        ___qtablewidgetitem14 = self.todoTable_a.horizontalHeaderItem(6)
        ___qtablewidgetitem14.setText(QCoreApplication.translate("MainWindow", u"Created Id", None));
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_11), QCoreApplication.translate("MainWindow", u"To Do List", None))
        self.sendMessage.setText(QCoreApplication.translate("MainWindow", u"Send", None))
        self.typeMessage.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Please Type Here", None))
        self.label_105.setText(QCoreApplication.translate("MainWindow", u"Select  Person", None))
        self.label_107.setText(QCoreApplication.translate("MainWindow", u"Select  Chat", None))
        self.label_115.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:16pt;\">Chat Box</span></p></body></html>", None))
        self.username.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><br/></p></body></html>", None))
        self.usermail.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><br/></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"Message_box", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Date Range", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"From", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"To", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Report Type", None))
        self.b6_2.setText(QCoreApplication.translate("MainWindow", u"Generate Report", None))
        self.b6_3.setText(QCoreApplication.translate("MainWindow", u"Export Report", None))
        ___qtablewidgetitem15 = self.tableWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem15.setText(QCoreApplication.translate("MainWindow", u"User", None));
        ___qtablewidgetitem16 = self.tableWidget.horizontalHeaderItem(1)
        ___qtablewidgetitem16.setText(QCoreApplication.translate("MainWindow", u"Action", None));
        ___qtablewidgetitem17 = self.tableWidget.horizontalHeaderItem(2)
        ___qtablewidgetitem17.setText(QCoreApplication.translate("MainWindow", u"Details", None));
        ___qtablewidgetitem18 = self.tableWidget.horizontalHeaderItem(3)
        ___qtablewidgetitem18.setText(QCoreApplication.translate("MainWindow", u"Process Date", None));
        ___qtablewidgetitem19 = self.tableWidget.horizontalHeaderItem(4)
        ___qtablewidgetitem19.setText(QCoreApplication.translate("MainWindow", u"Deadline", None));
        self.label_62.setText(QCoreApplication.translate("MainWindow", u"User", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QCoreApplication.translate("MainWindow", u"Reporting", None))
        self.menuTeacher.setTitle(QCoreApplication.translate("MainWindow", u"Users", None))
        self.menuMessage_Box.setTitle(QCoreApplication.translate("MainWindow", u"Message Box", None))
        self.menuExit.setTitle(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.menuReporting.setTitle(QCoreApplication.translate("MainWindow", u"Reporting", None))
        self.menuTeacher_Functions.setTitle(QCoreApplication.translate("MainWindow", u"Lessons", None))
        self.menuMeetings.setTitle(QCoreApplication.translate("MainWindow", u"Meetings", None))
        self.menuTo_Do_List.setTitle(QCoreApplication.translate("MainWindow", u"To Do List", None))
        self.menuAnnouncements.setTitle(QCoreApplication.translate("MainWindow", u"Announcements", None))
    # retranslateUi

