# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'student.ui'
##
## Created by: Qt User Interface Compiler version 6.6.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QHeaderView, QLabel,
    QLineEdit, QListView, QListWidget, QListWidgetItem,
    QMainWindow, QMenu, QMenuBar, QPushButton,
    QSizePolicy, QStatusBar, QTabWidget, QTableWidget,
    QTableWidgetItem, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1143, 809)
        self.menu11 = QAction(MainWindow)
        self.menu11.setObjectName(u"menu11")
        self.menu12 = QAction(MainWindow)
        self.menu12.setObjectName(u"menu12")
        self.menu21 = QAction(MainWindow)
        self.menu21.setObjectName(u"menu21")
        self.menu22 = QAction(MainWindow)
        self.menu22.setObjectName(u"menu22")
        self.menu31 = QAction(MainWindow)
        self.menu31.setObjectName(u"menu31")
        self.menu31_2 = QAction(MainWindow)
        self.menu31_2.setObjectName(u"menu31_2")
        self.menu32 = QAction(MainWindow)
        self.menu32.setObjectName(u"menu32")
        self.menu21_2 = QAction(MainWindow)
        self.menu21_2.setObjectName(u"menu21_2")
        self.menu22_2 = QAction(MainWindow)
        self.menu22_2.setObjectName(u"menu22_2")
        self.menu51_s = QAction(MainWindow)
        self.menu51_s.setObjectName(u"menu51_s")
        self.menu61_2 = QAction(MainWindow)
        self.menu61_2.setObjectName(u"menu61_2")
        self.menu71 = QAction(MainWindow)
        self.menu71.setObjectName(u"menu71")
        self.actionDSADADAD = QAction(MainWindow)
        self.actionDSADADAD.setObjectName(u"actionDSADADAD")
        self.announcements_s = QAction(MainWindow)
        self.announcements_s.setObjectName(u"announcements_s")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(0, 0, 1151, 61))
        font = QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setStrikeOut(False)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(u"color: rgb(253, 189, 16);\n"
"background-color: rgb(40, 41, 44);")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 60, 1161, 721))
        font1 = QFont()
        font1.setPointSize(10)
        font1.setBold(True)
        self.tabWidget.setFont(font1)
        self.tabWidget.setStyleSheet(u"background-color: rgb(40, 41, 44);")
        self.tab_1 = QWidget()
        self.tab_1.setObjectName(u"tab_1")
        self.label_13 = QLabel(self.tab_1)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(100, 120, 951, 51))
        font2 = QFont()
        font2.setPointSize(30)
        font2.setBold(True)
        font2.setStrikeOut(False)
        self.label_13.setFont(font2)
        self.label_13.setStyleSheet(u"color: rgb(253, 189, 16);\n"
"background-color: rgb(40, 41, 44);")
        self.label_14 = QLabel(self.tab_1)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(510, 200, 231, 31))
        font3 = QFont()
        font3.setPointSize(11)
        font3.setBold(True)
        font3.setUnderline(True)
        self.label_14.setFont(font3)
        self.label_14.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.label_12 = QLabel(self.tab_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(20, 30, 201, 31))
        font4 = QFont()
        font4.setPointSize(17)
        font4.setBold(True)
        font4.setUnderline(True)
        self.label_12.setFont(font4)
        self.label_12.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_24 = QLabel(self.tab_2)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(20, 330, 111, 20))
        font5 = QFont()
        font5.setPointSize(11)
        self.label_24.setFont(font5)
        self.label_24.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_26 = QLabel(self.tab_2)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(20, 180, 111, 20))
        self.label_26.setFont(font5)
        self.label_26.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.tb22 = QLineEdit(self.tab_2)
        self.tb22.setObjectName(u"tb22")
        self.tb22.setGeometry(QRect(140, 120, 271, 31))
        self.tb22.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_28 = QLabel(self.tab_2)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(20, 230, 111, 20))
        self.label_28.setFont(font5)
        self.label_28.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.tb24 = QLineEdit(self.tab_2)
        self.tb24.setObjectName(u"tb24")
        self.tb24.setGeometry(QRect(140, 220, 271, 31))
        self.tb24.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.tb25 = QLineEdit(self.tab_2)
        self.tb25.setObjectName(u"tb25")
        self.tb25.setGeometry(QRect(140, 270, 271, 31))
        self.tb25.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_29 = QLabel(self.tab_2)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(20, 280, 111, 20))
        self.label_29.setFont(font5)
        self.label_29.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.tb26 = QLineEdit(self.tab_2)
        self.tb26.setObjectName(u"tb26")
        self.tb26.setGeometry(QRect(140, 320, 271, 31))
        self.tb26.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_30 = QLabel(self.tab_2)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(20, 130, 111, 20))
        self.label_30.setFont(font5)
        self.label_30.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.b6 = QPushButton(self.tab_2)
        self.b6.setObjectName(u"b6")
        self.b6.setGeometry(QRect(140, 460, 271, 41))
        font6 = QFont()
        font6.setPointSize(11)
        font6.setBold(True)
        self.b6.setFont(font6)
        self.b6.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.tb23 = QLineEdit(self.tab_2)
        self.tb23.setObjectName(u"tb23")
        self.tb23.setGeometry(QRect(140, 170, 271, 31))
        self.tb23.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.tb27 = QLineEdit(self.tab_2)
        self.tb27.setObjectName(u"tb27")
        self.tb27.setGeometry(QRect(140, 410, 271, 31))
        font7 = QFont()
        font7.setPointSize(10)
        self.tb27.setFont(font7)
        self.tb27.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.tb27.setEchoMode(QLineEdit.Password)
        self.tb27.setClearButtonEnabled(True)
        self.label_16 = QLabel(self.tab_2)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(20, 370, 401, 20))
        self.label_16.setFont(font3)
        self.label_16.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.lesson_table = QTableWidget(self.tab_3)
        if (self.lesson_table.columnCount() < 5):
            self.lesson_table.setColumnCount(5)
        __qtablewidgetitem = QTableWidgetItem()
        self.lesson_table.setHorizontalHeaderItem(0, __qtablewidgetitem)
        font8 = QFont()
        font8.setPointSize(12)
        font8.setBold(True)
        __qtablewidgetitem1 = QTableWidgetItem()
        __qtablewidgetitem1.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        __qtablewidgetitem1.setFont(font8);
        self.lesson_table.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        __qtablewidgetitem2.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        __qtablewidgetitem2.setFont(font8);
        self.lesson_table.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        __qtablewidgetitem3.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        __qtablewidgetitem3.setFont(font8);
        self.lesson_table.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        __qtablewidgetitem4.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        __qtablewidgetitem4.setFont(font8);
        self.lesson_table.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        self.lesson_table.setObjectName(u"lesson_table")
        self.lesson_table.setGeometry(QRect(20, 60, 1111, 611))
        font9 = QFont()
        font9.setPointSize(12)
        font9.setBold(False)
        self.lesson_table.setFont(font9)
        self.lesson_table.setMouseTracking(False)
        self.lesson_table.setTabletTracking(False)
        self.lesson_table.setToolTipDuration(-1)
        self.lesson_table.setAutoFillBackground(False)
        self.lesson_table.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lesson_table.setSortingEnabled(False)
        self.lesson_table.horizontalHeader().setCascadingSectionResizes(False)
        self.lesson_table.horizontalHeader().setDefaultSectionSize(218)
        self.label_9 = QLabel(self.tab_3)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 20, 231, 31))
        self.label_9.setFont(font4)
        self.label_9.setToolTipDuration(-1)
        self.label_9.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_9.setIndent(0)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.records_list_1 = QListWidget(self.tab_4)
        self.records_list_1.setObjectName(u"records_list_1")
        self.records_list_1.setGeometry(QRect(30, 50, 1091, 621))
        self.records_list_1.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_116 = QLabel(self.tab_4)
        self.label_116.setObjectName(u"label_116")
        self.label_116.setGeometry(QRect(30, 10, 331, 31))
        self.label_116.setFont(font4)
        self.label_116.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.meeting_table = QTableWidget(self.tab_5)
        if (self.meeting_table.columnCount() < 3):
            self.meeting_table.setColumnCount(3)
        __qtablewidgetitem5 = QTableWidgetItem()
        __qtablewidgetitem5.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        __qtablewidgetitem5.setFont(font8);
        self.meeting_table.setHorizontalHeaderItem(0, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        __qtablewidgetitem6.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        __qtablewidgetitem6.setFont(font8);
        self.meeting_table.setHorizontalHeaderItem(1, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        __qtablewidgetitem7.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        __qtablewidgetitem7.setFont(font8);
        self.meeting_table.setHorizontalHeaderItem(2, __qtablewidgetitem7)
        self.meeting_table.setObjectName(u"meeting_table")
        self.meeting_table.setGeometry(QRect(20, 50, 1111, 621))
        self.meeting_table.setFont(font9)
        self.meeting_table.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.meeting_table.horizontalHeader().setDefaultSectionSize(368)
        self.label_27 = QLabel(self.tab_5)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(20, 10, 231, 31))
        self.label_27.setFont(font4)
        self.label_27.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.records_list_2 = QListWidget(self.tab_6)
        self.records_list_2.setObjectName(u"records_list_2")
        self.records_list_2.setGeometry(QRect(30, 50, 1091, 621))
        self.records_list_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_117 = QLabel(self.tab_6)
        self.label_117.setObjectName(u"label_117")
        self.label_117.setGeometry(QRect(30, 10, 351, 31))
        self.label_117.setFont(font4)
        self.label_117.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.label_122 = QLabel(self.tab)
        self.label_122.setObjectName(u"label_122")
        self.label_122.setGeometry(QRect(460, 40, 271, 51))
        font10 = QFont()
        font10.setPointSize(16)
        font10.setBold(True)
        self.label_122.setFont(font10)
        self.label_122.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.title_table = QTableWidget(self.tab)
        if (self.title_table.columnCount() < 3):
            self.title_table.setColumnCount(3)
        font11 = QFont()
        font11.setPointSize(13)
        font11.setBold(True)
        __qtablewidgetitem8 = QTableWidgetItem()
        __qtablewidgetitem8.setFont(font11);
        self.title_table.setHorizontalHeaderItem(0, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        __qtablewidgetitem9.setFont(font8);
        self.title_table.setHorizontalHeaderItem(1, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        __qtablewidgetitem10.setFont(font8);
        self.title_table.setHorizontalHeaderItem(2, __qtablewidgetitem10)
        self.title_table.setObjectName(u"title_table")
        self.title_table.setGeometry(QRect(20, 140, 1101, 461))
        self.title_table.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.tabWidget.addTab(self.tab, "")
        self.tab_7 = QWidget()
        self.tab_7.setObjectName(u"tab_7")
        self.list_view = QListView(self.tab_7)
        self.list_view.setObjectName(u"list_view")
        self.list_view.setGeometry(QRect(230, 190, 691, 341))
        self.list_view.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_108 = QLabel(self.tab_7)
        self.label_108.setObjectName(u"label_108")
        self.label_108.setGeometry(QRect(460, 40, 241, 61))
        font12 = QFont()
        font12.setPointSize(19)
        font12.setBold(True)
        self.label_108.setFont(font12)
        self.label_108.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.todoTable_s = QTableWidget(self.tab_7)
        if (self.todoTable_s.columnCount() < 7):
            self.todoTable_s.setColumnCount(7)
        __qtablewidgetitem11 = QTableWidgetItem()
        __qtablewidgetitem11.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        __qtablewidgetitem11.setFont(font8);
        self.todoTable_s.setHorizontalHeaderItem(0, __qtablewidgetitem11)
        __qtablewidgetitem12 = QTableWidgetItem()
        __qtablewidgetitem12.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        __qtablewidgetitem12.setFont(font8);
        self.todoTable_s.setHorizontalHeaderItem(1, __qtablewidgetitem12)
        __qtablewidgetitem13 = QTableWidgetItem()
        __qtablewidgetitem13.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        __qtablewidgetitem13.setFont(font8);
        self.todoTable_s.setHorizontalHeaderItem(2, __qtablewidgetitem13)
        __qtablewidgetitem14 = QTableWidgetItem()
        self.todoTable_s.setHorizontalHeaderItem(3, __qtablewidgetitem14)
        __qtablewidgetitem15 = QTableWidgetItem()
        __qtablewidgetitem15.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        __qtablewidgetitem15.setFont(font8);
        self.todoTable_s.setHorizontalHeaderItem(4, __qtablewidgetitem15)
        __qtablewidgetitem16 = QTableWidgetItem()
        self.todoTable_s.setHorizontalHeaderItem(5, __qtablewidgetitem16)
        __qtablewidgetitem17 = QTableWidgetItem()
        __qtablewidgetitem17.setFont(font8);
        self.todoTable_s.setHorizontalHeaderItem(6, __qtablewidgetitem17)
        self.todoTable_s.setObjectName(u"todoTable_s")
        self.todoTable_s.setGeometry(QRect(60, 160, 1031, 401))
        self.todoTable_s.setFont(font9)
        self.todoTable_s.setMouseTracking(False)
        self.todoTable_s.setTabletTracking(False)
        self.todoTable_s.setToolTipDuration(-1)
        self.todoTable_s.setAutoFillBackground(False)
        self.todoTable_s.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.todoTable_s.setSortingEnabled(False)
        self.todoTable_s.horizontalHeader().setCascadingSectionResizes(False)
        self.todoTable_s.horizontalHeader().setDefaultSectionSize(218)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QWidget()
        self.tab_8.setObjectName(u"tab_8")
        self.sendMessage = QPushButton(self.tab_8)
        self.sendMessage.setObjectName(u"sendMessage")
        self.sendMessage.setGeometry(QRect(860, 620, 201, 51))
        self.sendMessage.setFont(font6)
        self.sendMessage.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.listViewMessages = QListView(self.tab_8)
        self.listViewMessages.setObjectName(u"listViewMessages")
        self.listViewMessages.setGeometry(QRect(550, 120, 511, 371))
        self.listViewMessages.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.typeMessage = QLineEdit(self.tab_8)
        self.typeMessage.setObjectName(u"typeMessage")
        self.typeMessage.setGeometry(QRect(550, 540, 511, 71))
        font13 = QFont()
        font13.setBold(True)
        font13.setItalic(True)
        self.typeMessage.setFont(font13)
        self.typeMessage.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_105 = QLabel(self.tab_8)
        self.label_105.setObjectName(u"label_105")
        self.label_105.setGeometry(QRect(80, 30, 281, 21))
        self.label_105.setFont(font10)
        self.label_105.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.listView_chats = QListView(self.tab_8)
        self.listView_chats.setObjectName(u"listView_chats")
        self.listView_chats.setGeometry(QRect(80, 170, 401, 441))
        self.listView_chats.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.messageCombobox = QComboBox(self.tab_8)
        self.messageCombobox.setObjectName(u"messageCombobox")
        self.messageCombobox.setGeometry(QRect(80, 70, 401, 41))
        self.messageCombobox.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.label_147 = QLabel(self.tab_8)
        self.label_147.setObjectName(u"label_147")
        self.label_147.setGeometry(QRect(80, 140, 281, 21))
        self.label_147.setFont(font10)
        self.label_147.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_148 = QLabel(self.tab_8)
        self.label_148.setObjectName(u"label_148")
        self.label_148.setGeometry(QRect(550, 30, 501, 31))
        self.label_148.setFont(font10)
        self.label_148.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.username = QLabel(self.tab_8)
        self.username.setObjectName(u"username")
        self.username.setGeometry(QRect(550, 80, 281, 21))
        font14 = QFont()
        font14.setPointSize(18)
        font14.setBold(True)
        self.username.setFont(font14)
        self.username.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.usermail = QLabel(self.tab_8)
        self.usermail.setObjectName(u"usermail")
        self.usermail.setGeometry(QRect(850, 80, 201, 21))
        self.usermail.setFont(font9)
        self.usermail.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.usermail.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_149 = QLabel(self.tab_8)
        self.label_149.setObjectName(u"label_149")
        self.label_149.setGeometry(QRect(550, 500, 501, 31))
        self.label_149.setFont(font10)
        self.label_149.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.tabWidget.addTab(self.tab_8, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1143, 30))
        self.menubar.setStyleSheet(u"background-color: rgb(16, 16, 16);\n"
"color: rgb(255, 191, 16);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.menuStudent = QMenu(self.menubar)
        self.menuStudent.setObjectName(u"menuStudent")
        self.menuCourses = QMenu(self.menubar)
        self.menuCourses.setObjectName(u"menuCourses")
        self.menuMeetings = QMenu(self.menubar)
        self.menuMeetings.setObjectName(u"menuMeetings")
        self.menuTo_Do_List = QMenu(self.menubar)
        self.menuTo_Do_List.setObjectName(u"menuTo_Do_List")
        self.menuMessage_Box = QMenu(self.menubar)
        self.menuMessage_Box.setObjectName(u"menuMessage_Box")
        self.menuExit = QMenu(self.menubar)
        self.menuExit.setObjectName(u"menuExit")
        self.menuAnnouncements = QMenu(self.menubar)
        self.menuAnnouncements.setObjectName(u"menuAnnouncements")
        MainWindow.setMenuBar(self.menubar)

        self.menubar.addAction(self.menuStudent.menuAction())
        self.menubar.addAction(self.menuCourses.menuAction())
        self.menubar.addAction(self.menuMeetings.menuAction())
        self.menubar.addAction(self.menuTo_Do_List.menuAction())
        self.menubar.addAction(self.menuAnnouncements.menuAction())
        self.menubar.addAction(self.menuMessage_Box.menuAction())
        self.menubar.addAction(self.menuExit.menuAction())
        self.menuStudent.addAction(self.menu11)
        self.menuCourses.addAction(self.menu21_2)
        self.menuCourses.addAction(self.menu22_2)
        self.menuMeetings.addAction(self.menu31_2)
        self.menuMeetings.addAction(self.menu32)
        self.menuTo_Do_List.addAction(self.menu51_s)
        self.menuMessage_Box.addAction(self.menu61_2)
        self.menuExit.addAction(self.menu71)
        self.menuAnnouncements.addAction(self.announcements_s)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.menu11.setText(QCoreApplication.translate("MainWindow", u"Edit Profile", None))
        self.menu12.setText(QCoreApplication.translate("MainWindow", u"Edit Teacher", None))
        self.menu21.setText(QCoreApplication.translate("MainWindow", u"Add student", None))
        self.menu22.setText(QCoreApplication.translate("MainWindow", u"Edit student", None))
        self.menu31.setText(QCoreApplication.translate("MainWindow", u"Add/Edit Courses", None))
        self.menu31_2.setText(QCoreApplication.translate("MainWindow", u"View Mentor Meeting Schedule", None))
        self.menu32.setText(QCoreApplication.translate("MainWindow", u"View Mentor Meeting Attandance", None))
        self.menu21_2.setText(QCoreApplication.translate("MainWindow", u"View Lesson Schedule", None))
        self.menu22_2.setText(QCoreApplication.translate("MainWindow", u"View Lesson Attandance", None))
        self.menu51_s.setText(QCoreApplication.translate("MainWindow", u"View/React To Do List", None))
        self.menu61_2.setText(QCoreApplication.translate("MainWindow", u"View /Send Message", None))
        self.menu71.setText(QCoreApplication.translate("MainWindow", u"Logout", None))
        self.actionDSADADAD.setText(QCoreApplication.translate("MainWindow", u"View Messages", None))
        self.announcements_s.setText(QCoreApplication.translate("MainWindow", u"View Announcements", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"   \ue736   SMART SCHOOL > School-Learning-Enhancement-System   \ue736", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"   \ue736 WELCOME TO SMART SCHOOL \ue736", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"You login as student !!!", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), QCoreApplication.translate("MainWindow", u"Home", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Edit your profile", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"Phone", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"Name", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"Surname", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"City", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"Email", None))
        self.b6.setText(QCoreApplication.translate("MainWindow", u"Update your details", None))
        self.tb27.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Set password", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Enter your current Password / Set a new Password", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Edit Student", None))
        ___qtablewidgetitem = self.lesson_table.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Lesson ID", None));
        ___qtablewidgetitem1 = self.lesson_table.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Lesson", None));
        ___qtablewidgetitem2 = self.lesson_table.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Date", None));
        ___qtablewidgetitem3 = self.lesson_table.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"Time Slot", None));
        ___qtablewidgetitem4 = self.lesson_table.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"Instructor", None));
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Lesson Schedule", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"lesson_schedule", None))
        self.label_116.setText(QCoreApplication.translate("MainWindow", u"Lesson Attendance Records", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"lesson_attendance", None))
        ___qtablewidgetitem5 = self.meeting_table.horizontalHeaderItem(0)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"Meeting Title", None));
        ___qtablewidgetitem6 = self.meeting_table.horizontalHeaderItem(1)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("MainWindow", u"Meeting Date", None));
        ___qtablewidgetitem7 = self.meeting_table.horizontalHeaderItem(2)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("MainWindow", u"Meeting Time", None));
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"Meeting Schedule", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QCoreApplication.translate("MainWindow", u"meeting_schedule", None))
        self.label_117.setText(QCoreApplication.translate("MainWindow", u"Meeting Attendance Records", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QCoreApplication.translate("MainWindow", u"meeting_attendance", None))
        self.label_122.setText(QCoreApplication.translate("MainWindow", u"Announcements", None))
        ___qtablewidgetitem8 = self.title_table.horizontalHeaderItem(0)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("MainWindow", u"Title", None));
        ___qtablewidgetitem9 = self.title_table.horizontalHeaderItem(1)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("MainWindow", u"Announcement", None));
        ___qtablewidgetitem10 = self.title_table.horizontalHeaderItem(2)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("MainWindow", u"Deadline", None));
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"view_announcement", None))
        self.label_108.setText(QCoreApplication.translate("MainWindow", u"To Do List", None))
        ___qtablewidgetitem11 = self.todoTable_s.horizontalHeaderItem(0)
        ___qtablewidgetitem11.setText(QCoreApplication.translate("MainWindow", u"Status", None));
        ___qtablewidgetitem12 = self.todoTable_s.horizontalHeaderItem(1)
        ___qtablewidgetitem12.setText(QCoreApplication.translate("MainWindow", u"Task", None));
        ___qtablewidgetitem13 = self.todoTable_s.horizontalHeaderItem(2)
        ___qtablewidgetitem13.setText(QCoreApplication.translate("MainWindow", u"Deadline", None));
        ___qtablewidgetitem14 = self.todoTable_s.horizontalHeaderItem(3)
        ___qtablewidgetitem14.setText(QCoreApplication.translate("MainWindow", u"Task Id", None));
        ___qtablewidgetitem15 = self.todoTable_s.horizontalHeaderItem(4)
        ___qtablewidgetitem15.setText(QCoreApplication.translate("MainWindow", u"Student", None));
        ___qtablewidgetitem16 = self.todoTable_s.horizontalHeaderItem(5)
        ___qtablewidgetitem16.setText(QCoreApplication.translate("MainWindow", u"Created By Id", None));
        ___qtablewidgetitem17 = self.todoTable_s.horizontalHeaderItem(6)
        ___qtablewidgetitem17.setText(QCoreApplication.translate("MainWindow", u"Created By", None));
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), QCoreApplication.translate("MainWindow", u"view_todolist", None))
        self.sendMessage.setText(QCoreApplication.translate("MainWindow", u"Send", None))
        self.typeMessage.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Please Type Here", None))
        self.label_105.setText(QCoreApplication.translate("MainWindow", u"Select  Person", None))
        self.label_147.setText(QCoreApplication.translate("MainWindow", u"Select  Chat", None))
        self.label_148.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:16pt;\">Chat Box</span></p></body></html>", None))
        self.username.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><br/></p></body></html>", None))
        self.usermail.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><br/></p></body></html>", None))
        self.label_149.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Send a message</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), QCoreApplication.translate("MainWindow", u"message_box", None))
        self.menuStudent.setTitle(QCoreApplication.translate("MainWindow", u"Student", None))
        self.menuCourses.setTitle(QCoreApplication.translate("MainWindow", u"Lessons", None))
        self.menuMeetings.setTitle(QCoreApplication.translate("MainWindow", u"Meetings", None))
        self.menuTo_Do_List.setTitle(QCoreApplication.translate("MainWindow", u"To Do List", None))
        self.menuMessage_Box.setTitle(QCoreApplication.translate("MainWindow", u"Message Box", None))
        self.menuExit.setTitle(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.menuAnnouncements.setTitle(QCoreApplication.translate("MainWindow", u"Announcements", None))
    # retranslateUi

