# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'teacher.ui'
##
## Created by: Qt User Interface Compiler version 6.6.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QHeaderView,
    QLabel, QLineEdit, QListView, QListWidget,
    QListWidgetItem, QMainWindow, QMenu, QMenuBar,
    QPushButton, QSizePolicy, QStatusBar, QTabWidget,
    QTableWidget, QTableWidgetItem, QTextEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1116, 862)
        font = QFont()
        font.setPointSize(8)
        MainWindow.setFont(font)
        self.menu11 = QAction(MainWindow)
        self.menu11.setObjectName(u"menu11")
        self.menu12 = QAction(MainWindow)
        self.menu12.setObjectName(u"menu12")
        self.menu21 = QAction(MainWindow)
        self.menu21.setObjectName(u"menu21")
        self.menu22 = QAction(MainWindow)
        self.menu22.setObjectName(u"menu22")
        self.menu31_t = QAction(MainWindow)
        self.menu31_t.setObjectName(u"menu31_t")
        self.menu32_t = QAction(MainWindow)
        self.menu32_t.setObjectName(u"menu32_t")
        self.menu23_t = QAction(MainWindow)
        self.menu23_t.setObjectName(u"menu23_t")
        self.menu41_t = QAction(MainWindow)
        self.menu41_t.setObjectName(u"menu41_t")
        self.menu51_t = QAction(MainWindow)
        self.menu51_t.setObjectName(u"menu51_t")
        self.menu71_t = QAction(MainWindow)
        self.menu71_t.setObjectName(u"menu71_t")
        self.menu11_t = QAction(MainWindow)
        self.menu11_t.setObjectName(u"menu11_t")
        self.actionAdd = QAction(MainWindow)
        self.actionAdd.setObjectName(u"actionAdd")
        self.actionEdit = QAction(MainWindow)
        self.actionEdit.setObjectName(u"actionEdit")
        self.actionAdd_2 = QAction(MainWindow)
        self.actionAdd_2.setObjectName(u"actionAdd_2")
        self.actionEdit_2 = QAction(MainWindow)
        self.actionEdit_2.setObjectName(u"actionEdit_2")
        self.menu22_t_2 = QAction(MainWindow)
        self.menu22_t_2.setObjectName(u"menu22_t_2")
        self.menu21_t = QAction(MainWindow)
        self.menu21_t.setObjectName(u"menu21_t")
        self.menu22_t = QAction(MainWindow)
        self.menu22_t.setObjectName(u"menu22_t")
        self.menu32_t_2 = QAction(MainWindow)
        self.menu32_t_2.setObjectName(u"menu32_t_2")
        self.announcementMenu = QAction(MainWindow)
        self.announcementMenu.setObjectName(u"announcementMenu")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setFont(font)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(0, -20, 1121, 121))
        font1 = QFont()
        font1.setPointSize(17)
        font1.setBold(True)
        font1.setStrikeOut(False)
        self.label_3.setFont(font1)
        self.label_3.setToolTipDuration(-1)
        self.label_3.setStyleSheet(u"color: rgb(253, 189, 16);\n"
"background-color: rgb(40, 41, 44);")
        self.label_3.setIndent(0)
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 70, 1121, 741))
        font2 = QFont()
        font2.setPointSize(10)
        font2.setBold(True)
        self.tabWidget.setFont(font2)
        self.tabWidget.setToolTipDuration(-1)
        self.tabWidget.setStyleSheet(u"background-color: rgb(40, 41, 44);")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.label_14 = QLabel(self.tab_3)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(500, 220, 181, 41))
        font3 = QFont()
        font3.setPointSize(11)
        font3.setBold(True)
        font3.setUnderline(True)
        self.label_14.setFont(font3)
        self.label_14.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_13 = QLabel(self.tab_3)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(240, 160, 671, 41))
        font4 = QFont()
        font4.setPointSize(26)
        font4.setBold(True)
        font4.setStrikeOut(False)
        self.label_13.setFont(font4)
        self.label_13.setStyleSheet(u"color: rgb(253, 189, 16);\n"
"background-color: rgb(40, 41, 44);")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.tb25 = QLineEdit(self.tab_6)
        self.tb25.setObjectName(u"tb25")
        self.tb25.setGeometry(QRect(160, 290, 271, 31))
        self.tb25.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_29 = QLabel(self.tab_6)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(40, 250, 111, 20))
        font5 = QFont()
        font5.setPointSize(11)
        self.label_29.setFont(font5)
        self.label_29.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_16 = QLabel(self.tab_6)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(40, 390, 401, 20))
        self.label_16.setFont(font3)
        self.label_16.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.tb26 = QLineEdit(self.tab_6)
        self.tb26.setObjectName(u"tb26")
        self.tb26.setGeometry(QRect(160, 340, 271, 31))
        self.tb26.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_30 = QLabel(self.tab_6)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(40, 150, 111, 20))
        self.label_30.setFont(font5)
        self.label_30.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.tb22 = QLineEdit(self.tab_6)
        self.tb22.setObjectName(u"tb22")
        self.tb22.setGeometry(QRect(160, 140, 271, 31))
        self.tb22.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.tb23 = QLineEdit(self.tab_6)
        self.tb23.setObjectName(u"tb23")
        self.tb23.setGeometry(QRect(160, 190, 271, 31))
        self.tb23.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.b6 = QPushButton(self.tab_6)
        self.b6.setObjectName(u"b6")
        self.b6.setGeometry(QRect(160, 470, 271, 41))
        font6 = QFont()
        font6.setPointSize(11)
        font6.setBold(True)
        self.b6.setFont(font6)
        self.b6.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.label_31 = QLabel(self.tab_6)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(40, 200, 111, 20))
        self.label_31.setFont(font5)
        self.label_31.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.tb24 = QLineEdit(self.tab_6)
        self.tb24.setObjectName(u"tb24")
        self.tb24.setGeometry(QRect(160, 240, 271, 31))
        self.tb24.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_32 = QLabel(self.tab_6)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(40, 350, 111, 20))
        self.label_32.setFont(font5)
        self.label_32.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_33 = QLabel(self.tab_6)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(40, 300, 111, 20))
        self.label_33.setFont(font5)
        self.label_33.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.tb27 = QLineEdit(self.tab_6)
        self.tb27.setObjectName(u"tb27")
        self.tb27.setGeometry(QRect(160, 420, 271, 31))
        font7 = QFont()
        font7.setPointSize(10)
        self.tb27.setFont(font7)
        self.tb27.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.tb27.setEchoMode(QLineEdit.Password)
        self.tb27.setClearButtonEnabled(True)
        self.label_12 = QLabel(self.tab_6)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(40, 30, 201, 31))
        font8 = QFont()
        font8.setPointSize(17)
        font8.setBold(True)
        font8.setUnderline(True)
        self.label_12.setFont(font8)
        self.label_12.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.lessonScheduleContainer = QFrame(self.tab_2)
        self.lessonScheduleContainer.setObjectName(u"lessonScheduleContainer")
        self.lessonScheduleContainer.setGeometry(QRect(10, 0, 1111, 681))
        font9 = QFont()
        font9.setPointSize(25)
        font9.setUnderline(True)
        font9.setKerning(True)
        self.lessonScheduleContainer.setFont(font9)
        self.lessonScheduleContainer.setToolTipDuration(-1)
        self.lessonScheduleContainer.setFrameShape(QFrame.StyledPanel)
        self.lessonScheduleContainer.setFrameShadow(QFrame.Raised)
        self.dateInput = QLineEdit(self.lessonScheduleContainer)
        self.dateInput.setObjectName(u"dateInput")
        self.dateInput.setGeometry(QRect(170, 50, 311, 41))
        self.dateInput.setToolTipDuration(-1)
        self.dateInput.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.lessonName = QLineEdit(self.lessonScheduleContainer)
        self.lessonName.setObjectName(u"lessonName")
        self.lessonName.setGeometry(QRect(640, 50, 461, 41))
        font10 = QFont()
        font10.setFamilies([u"MS Shell Dlg 2"])
        font10.setPointSize(12)
        font10.setBold(False)
        font10.setItalic(False)
        font10.setUnderline(True)
        self.lessonName.setFont(font10)
        self.lessonName.setToolTipDuration(-1)
        self.lessonName.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.timeSlot = QLineEdit(self.lessonScheduleContainer)
        self.timeSlot.setObjectName(u"timeSlot")
        self.timeSlot.setGeometry(QRect(640, 100, 461, 41))
        self.timeSlot.setToolTipDuration(-1)
        self.timeSlot.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.addLessonBtn = QPushButton(self.lessonScheduleContainer)
        self.addLessonBtn.setObjectName(u"addLessonBtn")
        self.addLessonBtn.setGeometry(QRect(950, 150, 151, 41))
        self.addLessonBtn.setFont(font6)
        self.addLessonBtn.setToolTipDuration(-1)
        self.addLessonBtn.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.label_2 = QLabel(self.lessonScheduleContainer)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 10, 231, 31))
        self.label_2.setFont(font8)
        self.label_2.setToolTipDuration(-1)
        self.label_2.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_2.setIndent(0)
        self.deleteLessonBtn = QPushButton(self.lessonScheduleContainer)
        self.deleteLessonBtn.setObjectName(u"deleteLessonBtn")
        self.deleteLessonBtn.setGeometry(QRect(10, 630, 141, 41))
        self.deleteLessonBtn.setFont(font6)
        self.deleteLessonBtn.setToolTipDuration(-1)
        self.deleteLessonBtn.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.deleteAllLessonsBtn = QPushButton(self.lessonScheduleContainer)
        self.deleteAllLessonsBtn.setObjectName(u"deleteAllLessonsBtn")
        self.deleteAllLessonsBtn.setGeometry(QRect(940, 630, 161, 41))
        self.deleteAllLessonsBtn.setFont(font6)
        self.deleteAllLessonsBtn.setToolTipDuration(-1)
        self.deleteAllLessonsBtn.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.lessonTable = QTableWidget(self.lessonScheduleContainer)
        if (self.lessonTable.columnCount() < 5):
            self.lessonTable.setColumnCount(5)
        __qtablewidgetitem = QTableWidgetItem()
        self.lessonTable.setHorizontalHeaderItem(0, __qtablewidgetitem)
        font11 = QFont()
        font11.setPointSize(12)
        font11.setBold(True)
        __qtablewidgetitem1 = QTableWidgetItem()
        __qtablewidgetitem1.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        __qtablewidgetitem1.setFont(font11);
        self.lessonTable.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        __qtablewidgetitem2.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        __qtablewidgetitem2.setFont(font11);
        self.lessonTable.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        __qtablewidgetitem3.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        __qtablewidgetitem3.setFont(font11);
        self.lessonTable.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        __qtablewidgetitem4.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        __qtablewidgetitem4.setFont(font11);
        self.lessonTable.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        self.lessonTable.setObjectName(u"lessonTable")
        self.lessonTable.setGeometry(QRect(10, 200, 1095, 421))
        font12 = QFont()
        font12.setPointSize(12)
        font12.setBold(False)
        self.lessonTable.setFont(font12)
        self.lessonTable.setMouseTracking(False)
        self.lessonTable.setTabletTracking(False)
        self.lessonTable.setToolTipDuration(-1)
        self.lessonTable.setAutoFillBackground(False)
        self.lessonTable.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lessonTable.setSortingEnabled(False)
        self.lessonTable.horizontalHeader().setCascadingSectionResizes(False)
        self.lessonTable.horizontalHeader().setDefaultSectionSize(218)
        self.label_5 = QLabel(self.lessonScheduleContainer)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(50, 60, 111, 21))
        font13 = QFont()
        font13.setPointSize(11)
        font13.setBold(True)
        font13.setUnderline(False)
        font13.setKerning(True)
        self.label_5.setFont(font13)
        self.label_5.setToolTipDuration(-1)
        self.label_5.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_5.setIndent(0)
        self.label_6 = QLabel(self.lessonScheduleContainer)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(510, 60, 121, 21))
        self.label_6.setFont(font13)
        self.label_6.setToolTipDuration(-1)
        self.label_6.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_6.setIndent(0)
        self.label_7 = QLabel(self.lessonScheduleContainer)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(490, 110, 141, 21))
        self.label_7.setFont(font13)
        self.label_7.setToolTipDuration(-1)
        self.label_7.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_7.setIndent(0)
        self.label_9 = QLabel(self.lessonScheduleContainer)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 170, 231, 21))
        self.label_9.setFont(font8)
        self.label_9.setToolTipDuration(-1)
        self.label_9.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_9.setIndent(0)
        self.comboBox_instructor = QComboBox(self.lessonScheduleContainer)
        self.comboBox_instructor.setObjectName(u"comboBox_instructor")
        self.comboBox_instructor.setGeometry(QRect(170, 100, 311, 41))
        font14 = QFont()
        font14.setPointSize(12)
        self.comboBox_instructor.setFont(font14)
        self.comboBox_instructor.setToolTipDuration(0)
        self.comboBox_instructor.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.comboBox_instructor.setMaxVisibleItems(30)
        self.comboBox_instructor.setMinimumContentsLength(6)
        self.label_18 = QLabel(self.lessonScheduleContainer)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(10, 110, 151, 21))
        self.label_18.setFont(font13)
        self.label_18.setToolTipDuration(-1)
        self.label_18.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_18.setIndent(0)
        self.resetLessonBtn = QPushButton(self.lessonScheduleContainer)
        self.resetLessonBtn.setObjectName(u"resetLessonBtn")
        self.resetLessonBtn.setGeometry(QRect(790, 150, 151, 41))
        self.resetLessonBtn.setFont(font6)
        self.resetLessonBtn.setToolTipDuration(-1)
        self.resetLessonBtn.setStyleSheet(u"background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255)")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_17 = QWidget()
        self.tab_17.setObjectName(u"tab_17")
        self.label_57 = QLabel(self.tab_17)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setGeometry(QRect(20, 20, 481, 31))
        self.label_57.setFont(font8)
        self.label_57.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.markAttendanceBtn = QPushButton(self.tab_17)
        self.markAttendanceBtn.setObjectName(u"markAttendanceBtn")
        self.markAttendanceBtn.setGeometry(QRect(980, 120, 131, 41))
        self.markAttendanceBtn.setFont(font11)
        self.markAttendanceBtn.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.lessonComboBox = QComboBox(self.tab_17)
        self.lessonComboBox.setObjectName(u"lessonComboBox")
        self.lessonComboBox.setGeometry(QRect(150, 120, 581, 41))
        self.lessonComboBox.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.studentComboBox = QComboBox(self.tab_17)
        self.studentComboBox.setObjectName(u"studentComboBox")
        self.studentComboBox.setGeometry(QRect(150, 60, 351, 41))
        self.studentComboBox.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_103 = QLabel(self.tab_17)
        self.label_103.setObjectName(u"label_103")
        self.label_103.setGeometry(QRect(20, 130, 121, 21))
        self.label_103.setFont(font11)
        self.label_103.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_109 = QLabel(self.tab_17)
        self.label_109.setObjectName(u"label_109")
        self.label_109.setGeometry(QRect(20, 70, 121, 21))
        self.label_109.setFont(font11)
        self.label_109.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_110 = QLabel(self.tab_17)
        self.label_110.setObjectName(u"label_110")
        self.label_110.setGeometry(QRect(770, 90, 161, 21))
        self.label_110.setFont(font11)
        self.label_110.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.statusComboBox = QComboBox(self.tab_17)
        self.statusComboBox.addItem("")
        self.statusComboBox.addItem("")
        self.statusComboBox.addItem("")
        self.statusComboBox.setObjectName(u"statusComboBox")
        self.statusComboBox.setGeometry(QRect(770, 120, 171, 41))
        self.statusComboBox.setFont(font14)
        self.statusComboBox.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.recordsList = QListWidget(self.tab_17)
        self.recordsList.setObjectName(u"recordsList")
        self.recordsList.setGeometry(QRect(20, 240, 1091, 401))
        self.recordsList.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_111 = QLabel(self.tab_17)
        self.label_111.setObjectName(u"label_111")
        self.label_111.setGeometry(QRect(20, 210, 181, 21))
        self.label_111.setFont(font11)
        self.label_111.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.deleteAttendanceBtn = QPushButton(self.tab_17)
        self.deleteAttendanceBtn.setObjectName(u"deleteAttendanceBtn")
        self.deleteAttendanceBtn.setGeometry(QRect(20, 650, 201, 41))
        self.deleteAttendanceBtn.setFont(font6)
        self.deleteAttendanceBtn.setToolTipDuration(-1)
        self.deleteAttendanceBtn.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.deleteAllAttendanceBtn = QPushButton(self.tab_17)
        self.deleteAllAttendanceBtn.setObjectName(u"deleteAllAttendanceBtn")
        self.deleteAllAttendanceBtn.setGeometry(QRect(950, 650, 161, 41))
        self.deleteAllAttendanceBtn.setFont(font6)
        self.deleteAllAttendanceBtn.setToolTipDuration(-1)
        self.deleteAllAttendanceBtn.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.deleteSelectedStudentAttendanceBtn = QPushButton(self.tab_17)
        self.deleteSelectedStudentAttendanceBtn.setObjectName(u"deleteSelectedStudentAttendanceBtn")
        self.deleteSelectedStudentAttendanceBtn.setGeometry(QRect(290, 650, 341, 41))
        self.deleteSelectedStudentAttendanceBtn.setFont(font6)
        self.deleteSelectedStudentAttendanceBtn.setToolTipDuration(-1)
        self.deleteSelectedStudentAttendanceBtn.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.tabWidget.addTab(self.tab_17, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.meetingScheduleContainer = QFrame(self.tab_4)
        self.meetingScheduleContainer.setObjectName(u"meetingScheduleContainer")
        self.meetingScheduleContainer.setGeometry(QRect(10, 0, 1111, 681))
        self.meetingScheduleContainer.setFont(font9)
        self.meetingScheduleContainer.setFrameShape(QFrame.StyledPanel)
        self.meetingScheduleContainer.setFrameShadow(QFrame.Raised)
        self.meetingDateInput = QLineEdit(self.meetingScheduleContainer)
        self.meetingDateInput.setObjectName(u"meetingDateInput")
        self.meetingDateInput.setGeometry(QRect(20, 90, 311, 41))
        self.meetingDateInput.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.meetingTitle = QLineEdit(self.meetingScheduleContainer)
        self.meetingTitle.setObjectName(u"meetingTitle")
        self.meetingTitle.setGeometry(QRect(20, 180, 311, 41))
        self.meetingTitle.setFont(font10)
        self.meetingTitle.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.meetingTimeSlot = QLineEdit(self.meetingScheduleContainer)
        self.meetingTimeSlot.setObjectName(u"meetingTimeSlot")
        self.meetingTimeSlot.setGeometry(QRect(20, 270, 311, 41))
        self.meetingTimeSlot.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.addMeetingBtn = QPushButton(self.meetingScheduleContainer)
        self.addMeetingBtn.setObjectName(u"addMeetingBtn")
        self.addMeetingBtn.setGeometry(QRect(180, 330, 151, 41))
        self.addMeetingBtn.setFont(font6)
        self.addMeetingBtn.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.label_4 = QLabel(self.meetingScheduleContainer)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 20, 241, 31))
        self.label_4.setFont(font8)
        self.label_4.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.deleteMeetingBtn = QPushButton(self.meetingScheduleContainer)
        self.deleteMeetingBtn.setObjectName(u"deleteMeetingBtn")
        self.deleteMeetingBtn.setGeometry(QRect(370, 620, 141, 41))
        self.deleteMeetingBtn.setFont(font6)
        self.deleteMeetingBtn.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.deleteAllMeetingsBtn = QPushButton(self.meetingScheduleContainer)
        self.deleteAllMeetingsBtn.setObjectName(u"deleteAllMeetingsBtn")
        self.deleteAllMeetingsBtn.setGeometry(QRect(930, 620, 161, 41))
        self.deleteAllMeetingsBtn.setFont(font6)
        self.deleteAllMeetingsBtn.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.meetingTable = QTableWidget(self.meetingScheduleContainer)
        if (self.meetingTable.columnCount() < 3):
            self.meetingTable.setColumnCount(3)
        __qtablewidgetitem5 = QTableWidgetItem()
        __qtablewidgetitem5.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        __qtablewidgetitem5.setFont(font11);
        self.meetingTable.setHorizontalHeaderItem(0, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        __qtablewidgetitem6.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        __qtablewidgetitem6.setFont(font11);
        self.meetingTable.setHorizontalHeaderItem(1, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        __qtablewidgetitem7.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        __qtablewidgetitem7.setFont(font11);
        self.meetingTable.setHorizontalHeaderItem(2, __qtablewidgetitem7)
        self.meetingTable.setObjectName(u"meetingTable")
        self.meetingTable.setGeometry(QRect(370, 90, 721, 521))
        self.meetingTable.setFont(font12)
        self.meetingTable.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.meetingTable.horizontalHeader().setDefaultSectionSize(239)
        self.label_10 = QLabel(self.meetingScheduleContainer)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 60, 111, 21))
        font15 = QFont()
        font15.setPointSize(11)
        font15.setBold(True)
        font15.setUnderline(True)
        font15.setKerning(True)
        self.label_10.setFont(font15)
        self.label_10.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_11 = QLabel(self.meetingScheduleContainer)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 150, 111, 21))
        self.label_11.setFont(font15)
        self.label_11.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_15 = QLabel(self.meetingScheduleContainer)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 240, 141, 21))
        self.label_15.setFont(font15)
        self.label_15.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_17 = QLabel(self.meetingScheduleContainer)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(370, 20, 231, 31))
        self.label_17.setFont(font8)
        self.label_17.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.resetMeetingBtn = QPushButton(self.meetingScheduleContainer)
        self.resetMeetingBtn.setObjectName(u"resetMeetingBtn")
        self.resetMeetingBtn.setGeometry(QRect(20, 330, 151, 41))
        self.resetMeetingBtn.setFont(font6)
        self.resetMeetingBtn.setToolTipDuration(-1)
        self.resetMeetingBtn.setStyleSheet(u"background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255)")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_7 = QWidget()
        self.tab_7.setObjectName(u"tab_7")
        self.label_106 = QLabel(self.tab_7)
        self.label_106.setObjectName(u"label_106")
        self.label_106.setGeometry(QRect(20, 10, 461, 31))
        self.label_106.setFont(font8)
        self.label_106.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.deleteAttendanceBtn_2 = QPushButton(self.tab_7)
        self.deleteAttendanceBtn_2.setObjectName(u"deleteAttendanceBtn_2")
        self.deleteAttendanceBtn_2.setGeometry(QRect(20, 640, 201, 41))
        self.deleteAttendanceBtn_2.setFont(font6)
        self.deleteAttendanceBtn_2.setToolTipDuration(-1)
        self.deleteAttendanceBtn_2.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.label_112 = QLabel(self.tab_7)
        self.label_112.setObjectName(u"label_112")
        self.label_112.setGeometry(QRect(20, 60, 121, 21))
        self.label_112.setFont(font11)
        self.label_112.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.meetingComboBox_2 = QComboBox(self.tab_7)
        self.meetingComboBox_2.setObjectName(u"meetingComboBox_2")
        self.meetingComboBox_2.setGeometry(QRect(150, 110, 581, 41))
        self.meetingComboBox_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.statusComboBox_2 = QComboBox(self.tab_7)
        self.statusComboBox_2.addItem("")
        self.statusComboBox_2.addItem("")
        self.statusComboBox_2.addItem("")
        self.statusComboBox_2.setObjectName(u"statusComboBox_2")
        self.statusComboBox_2.setGeometry(QRect(770, 110, 171, 41))
        self.statusComboBox_2.setFont(font14)
        self.statusComboBox_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.deleteSelectedStudentAttendanceBtn_2 = QPushButton(self.tab_7)
        self.deleteSelectedStudentAttendanceBtn_2.setObjectName(u"deleteSelectedStudentAttendanceBtn_2")
        self.deleteSelectedStudentAttendanceBtn_2.setGeometry(QRect(290, 640, 341, 41))
        self.deleteSelectedStudentAttendanceBtn_2.setFont(font6)
        self.deleteSelectedStudentAttendanceBtn_2.setToolTipDuration(-1)
        self.deleteSelectedStudentAttendanceBtn_2.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.studentComboBox_2 = QComboBox(self.tab_7)
        self.studentComboBox_2.setObjectName(u"studentComboBox_2")
        self.studentComboBox_2.setGeometry(QRect(150, 50, 351, 41))
        self.studentComboBox_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_113 = QLabel(self.tab_7)
        self.label_113.setObjectName(u"label_113")
        self.label_113.setGeometry(QRect(770, 80, 161, 21))
        self.label_113.setFont(font11)
        self.label_113.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.markAttendanceBtn_2 = QPushButton(self.tab_7)
        self.markAttendanceBtn_2.setObjectName(u"markAttendanceBtn_2")
        self.markAttendanceBtn_2.setGeometry(QRect(980, 110, 131, 41))
        self.markAttendanceBtn_2.setFont(font11)
        self.markAttendanceBtn_2.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.label_114 = QLabel(self.tab_7)
        self.label_114.setObjectName(u"label_114")
        self.label_114.setGeometry(QRect(20, 200, 241, 21))
        self.label_114.setFont(font11)
        self.label_114.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.deleteAllAttendanceBtn_2 = QPushButton(self.tab_7)
        self.deleteAllAttendanceBtn_2.setObjectName(u"deleteAllAttendanceBtn_2")
        self.deleteAllAttendanceBtn_2.setGeometry(QRect(950, 640, 161, 41))
        self.deleteAllAttendanceBtn_2.setFont(font6)
        self.deleteAllAttendanceBtn_2.setToolTipDuration(-1)
        self.deleteAllAttendanceBtn_2.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.label_104 = QLabel(self.tab_7)
        self.label_104.setObjectName(u"label_104")
        self.label_104.setGeometry(QRect(20, 120, 121, 21))
        self.label_104.setFont(font11)
        self.label_104.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.recordsList_2 = QListWidget(self.tab_7)
        self.recordsList_2.setObjectName(u"recordsList_2")
        self.recordsList_2.setGeometry(QRect(20, 230, 1091, 401))
        self.recordsList_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.announcementTitle = QLineEdit(self.tab)
        self.announcementTitle.setObjectName(u"announcementTitle")
        self.announcementTitle.setGeometry(QRect(190, 140, 321, 51))
        font16 = QFont()
        font16.setBold(True)
        font16.setItalic(True)
        self.announcementTitle.setFont(font16)
        self.announcementTitle.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.textEdit = QTextEdit(self.tab)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(190, 220, 321, 271))
        self.textEdit.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.textEdit.setInputMethodHints(Qt.ImhMultiLine)
        self.addButton = QPushButton(self.tab)
        self.addButton.setObjectName(u"addButton")
        self.addButton.setGeometry(QRect(190, 510, 91, 51))
        self.addButton.setFont(font6)
        self.addButton.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.editButton = QPushButton(self.tab)
        self.editButton.setObjectName(u"editButton")
        self.editButton.setGeometry(QRect(300, 510, 101, 51))
        self.editButton.setFont(font6)
        self.editButton.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.deleteButton = QPushButton(self.tab)
        self.deleteButton.setObjectName(u"deleteButton")
        self.deleteButton.setGeometry(QRect(420, 510, 91, 51))
        self.deleteButton.setFont(font6)
        self.deleteButton.setStyleSheet(u"background-color: rgb(170, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.announcementCombobox = QComboBox(self.tab)
        self.announcementCombobox.setObjectName(u"announcementCombobox")
        self.announcementCombobox.setGeometry(QRect(610, 60, 471, 51))
        self.announcementCombobox.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_58 = QLabel(self.tab)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setGeometry(QRect(20, 20, 501, 51))
        font17 = QFont()
        font17.setPointSize(18)
        font17.setBold(True)
        self.label_58.setFont(font17)
        self.label_58.setStyleSheet(u"color: rgb(255, 191, 16);\n"
"fontSize: 20px")
        self.label_65 = QLabel(self.tab)
        self.label_65.setObjectName(u"label_65")
        self.label_65.setGeometry(QRect(610, 160, 231, 31))
        font18 = QFont()
        font18.setPointSize(14)
        font18.setBold(True)
        self.label_65.setFont(font18)
        self.label_65.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.announcementListView = QListView(self.tab)
        self.announcementListView.setObjectName(u"announcementListView")
        self.announcementListView.setGeometry(QRect(610, 200, 471, 421))
        self.announcementListView.setStyleSheet(u"background: rgb(255, 255, 255)")
        self.announcementDate = QLineEdit(self.tab)
        self.announcementDate.setObjectName(u"announcementDate")
        self.announcementDate.setGeometry(QRect(190, 80, 321, 41))
        self.announcementDate.setToolTipDuration(-1)
        self.announcementDate.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.label_66 = QLabel(self.tab)
        self.label_66.setObjectName(u"label_66")
        self.label_66.setGeometry(QRect(20, 80, 151, 31))
        self.label_66.setFont(font18)
        self.label_66.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_67 = QLabel(self.tab)
        self.label_67.setObjectName(u"label_67")
        self.label_67.setGeometry(QRect(20, 150, 151, 31))
        self.label_67.setFont(font18)
        self.label_67.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_68 = QLabel(self.tab)
        self.label_68.setObjectName(u"label_68")
        self.label_68.setGeometry(QRect(20, 220, 151, 41))
        self.label_68.setFont(font18)
        self.label_68.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_69 = QLabel(self.tab)
        self.label_69.setObjectName(u"label_69")
        self.label_69.setGeometry(QRect(610, 20, 481, 41))
        self.label_69.setFont(font17)
        self.label_69.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.tabWidget.addTab(self.tab, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.deadlineInput = QLineEdit(self.tab_5)
        self.deadlineInput.setObjectName(u"deadlineInput")
        self.deadlineInput.setGeometry(QRect(500, 80, 411, 41))
        self.deadlineInput.setToolTipDuration(-1)
        self.deadlineInput.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.todoTable = QTableWidget(self.tab_5)
        if (self.todoTable.columnCount() < 7):
            self.todoTable.setColumnCount(7)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.todoTable.setHorizontalHeaderItem(0, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        __qtablewidgetitem9.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        __qtablewidgetitem9.setFont(font11);
        self.todoTable.setHorizontalHeaderItem(1, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        __qtablewidgetitem10.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        __qtablewidgetitem10.setFont(font11);
        self.todoTable.setHorizontalHeaderItem(2, __qtablewidgetitem10)
        __qtablewidgetitem11 = QTableWidgetItem()
        __qtablewidgetitem11.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        __qtablewidgetitem11.setFont(font11);
        self.todoTable.setHorizontalHeaderItem(3, __qtablewidgetitem11)
        font19 = QFont()
        font19.setFamilies([u"MS Shell Dlg 2"])
        font19.setPointSize(12)
        font19.setBold(True)
        __qtablewidgetitem12 = QTableWidgetItem()
        __qtablewidgetitem12.setFont(font19);
        self.todoTable.setHorizontalHeaderItem(4, __qtablewidgetitem12)
        __qtablewidgetitem13 = QTableWidgetItem()
        __qtablewidgetitem13.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        __qtablewidgetitem13.setFont(font11);
        self.todoTable.setHorizontalHeaderItem(5, __qtablewidgetitem13)
        __qtablewidgetitem14 = QTableWidgetItem()
        __qtablewidgetitem14.setFont(font19);
        self.todoTable.setHorizontalHeaderItem(6, __qtablewidgetitem14)
        self.todoTable.setObjectName(u"todoTable")
        self.todoTable.setGeometry(QRect(50, 210, 1051, 401))
        self.todoTable.setFont(font12)
        self.todoTable.setMouseTracking(False)
        self.todoTable.setTabletTracking(False)
        self.todoTable.setToolTipDuration(-1)
        self.todoTable.setAutoFillBackground(False)
        self.todoTable.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.todoTable.setSortingEnabled(False)
        self.todoTable.horizontalHeader().setCascadingSectionResizes(False)
        self.todoTable.horizontalHeader().setDefaultSectionSize(218)
        self.label_44 = QLabel(self.tab_5)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(50, 90, 71, 21))
        font20 = QFont()
        font20.setPointSize(14)
        font20.setBold(True)
        font20.setUnderline(True)
        self.label_44.setFont(font20)
        self.label_44.setToolTipDuration(-1)
        self.label_44.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_44.setIndent(0)
        self.todoName = QLineEdit(self.tab_5)
        self.todoName.setObjectName(u"todoName")
        self.todoName.setGeometry(QRect(150, 150, 761, 41))
        self.todoName.setFont(font10)
        self.todoName.setToolTipDuration(-1)
        self.todoName.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.todoName.setAlignment(Qt.AlignCenter)
        self.deleteAllTodosBtn = QPushButton(self.tab_5)
        self.deleteAllTodosBtn.setObjectName(u"deleteAllTodosBtn")
        self.deleteAllTodosBtn.setGeometry(QRect(920, 620, 161, 41))
        self.deleteAllTodosBtn.setFont(font6)
        self.deleteAllTodosBtn.setToolTipDuration(-1)
        self.deleteAllTodosBtn.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.resAllTodoFields = QPushButton(self.tab_5)
        self.resAllTodoFields.setObjectName(u"resAllTodoFields")
        self.resAllTodoFields.setGeometry(QRect(920, 80, 161, 41))
        self.resAllTodoFields.setFont(font6)
        self.resAllTodoFields.setToolTipDuration(-1)
        self.resAllTodoFields.setStyleSheet(u"background-color: rgb(255, 191, 16);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 0, 0);")
        self.label_42 = QLabel(self.tab_5)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(450, 30, 211, 21))
        font21 = QFont()
        font21.setPointSize(16)
        font21.setBold(True)
        font21.setUnderline(True)
        self.label_42.setFont(font21)
        self.label_42.setToolTipDuration(-1)
        self.label_42.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_42.setIndent(0)
        self.allTodosBtn = QPushButton(self.tab_5)
        self.allTodosBtn.setObjectName(u"allTodosBtn")
        self.allTodosBtn.setGeometry(QRect(380, 80, 111, 41))
        self.allTodosBtn.setFont(font6)
        self.allTodosBtn.setToolTipDuration(-1)
        self.allTodosBtn.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.addTodoBtn = QPushButton(self.tab_5)
        self.addTodoBtn.setObjectName(u"addTodoBtn")
        self.addTodoBtn.setGeometry(QRect(920, 130, 161, 61))
        self.addTodoBtn.setFont(font6)
        self.addTodoBtn.setToolTipDuration(-1)
        self.addTodoBtn.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.deleteTodoBtn = QPushButton(self.tab_5)
        self.deleteTodoBtn.setObjectName(u"deleteTodoBtn")
        self.deleteTodoBtn.setGeometry(QRect(50, 620, 141, 41))
        self.deleteTodoBtn.setFont(font6)
        self.deleteTodoBtn.setToolTipDuration(-1)
        self.deleteTodoBtn.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.comboBox_student = QComboBox(self.tab_5)
        self.comboBox_student.setObjectName(u"comboBox_student")
        self.comboBox_student.setGeometry(QRect(150, 80, 231, 41))
        self.comboBox_student.setFont(font14)
        self.comboBox_student.setToolTipDuration(0)
        self.comboBox_student.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.comboBox_student.setMaxVisibleItems(30)
        self.comboBox_student.setMinimumContentsLength(6)
        self.label_43 = QLabel(self.tab_5)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(40, 160, 101, 21))
        font22 = QFont()
        font22.setPointSize(12)
        font22.setBold(True)
        font22.setUnderline(True)
        self.label_43.setFont(font22)
        self.label_43.setToolTipDuration(-1)
        self.label_43.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_43.setIndent(0)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_8 = QWidget()
        self.tab_8.setObjectName(u"tab_8")
        self.typeMessage = QLineEdit(self.tab_8)
        self.typeMessage.setObjectName(u"typeMessage")
        self.typeMessage.setGeometry(QRect(550, 520, 501, 71))
        self.typeMessage.setFont(font16)
        self.typeMessage.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.sendMessage = QPushButton(self.tab_8)
        self.sendMessage.setObjectName(u"sendMessage")
        self.sendMessage.setGeometry(QRect(850, 620, 201, 51))
        self.sendMessage.setFont(font6)
        self.sendMessage.setStyleSheet(u"background-color: rgb(255, 191, 16);")
        self.label_105 = QLabel(self.tab_8)
        self.label_105.setObjectName(u"label_105")
        self.label_105.setGeometry(QRect(80, 50, 281, 21))
        self.label_105.setFont(font11)
        self.label_105.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.listView_chats = QListView(self.tab_8)
        self.listView_chats.setObjectName(u"listView_chats")
        self.listView_chats.setGeometry(QRect(80, 210, 401, 381))
        self.listView_chats.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.listViewMessages = QListView(self.tab_8)
        self.listViewMessages.setObjectName(u"listViewMessages")
        self.listViewMessages.setGeometry(QRect(550, 150, 501, 361))
        self.listViewMessages.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.messageCombobox = QComboBox(self.tab_8)
        self.messageCombobox.setObjectName(u"messageCombobox")
        self.messageCombobox.setGeometry(QRect(80, 100, 401, 41))
        self.messageCombobox.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_107 = QLabel(self.tab_8)
        self.label_107.setObjectName(u"label_107")
        self.label_107.setGeometry(QRect(80, 170, 281, 21))
        self.label_107.setFont(font11)
        self.label_107.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.label_115 = QLabel(self.tab_8)
        self.label_115.setObjectName(u"label_115")
        self.label_115.setGeometry(QRect(550, 50, 461, 31))
        font23 = QFont()
        font23.setPointSize(16)
        font23.setBold(True)
        self.label_115.setFont(font23)
        self.label_115.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.username = QLabel(self.tab_8)
        self.username.setObjectName(u"username")
        self.username.setGeometry(QRect(550, 100, 281, 21))
        self.username.setFont(font17)
        self.username.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.usermail = QLabel(self.tab_8)
        self.usermail.setObjectName(u"usermail")
        self.usermail.setGeometry(QRect(850, 100, 201, 21))
        self.usermail.setFont(font12)
        self.usermail.setStyleSheet(u"color: rgb(255, 191, 16);")
        self.usermail.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.tabWidget.addTab(self.tab_8, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1116, 50))
        self.menubar.setMinimumSize(QSize(600, 50))
        self.menubar.setMaximumSize(QSize(16777215, 16777215))
        self.menubar.setSizeIncrement(QSize(0, 0))
        self.menubar.setBaseSize(QSize(0, 0))
        font24 = QFont()
        font24.setFamilies([u"MS Shell Dlg 2"])
        font24.setPointSize(16)
        font24.setBold(False)
        font24.setItalic(False)
        font24.setUnderline(False)
        font24.setStrikeOut(False)
        self.menubar.setFont(font24)
        self.menubar.setStyleSheet(u"background-color: rgb(16, 16, 16);\n"
"color: rgb(255, 191, 16);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.menuAttandance = QMenu(self.menubar)
        self.menuAttandance.setObjectName(u"menuAttandance")
        self.menuMeetings = QMenu(self.menubar)
        self.menuMeetings.setObjectName(u"menuMeetings")
        self.menuTo_Do_List = QMenu(self.menubar)
        self.menuTo_Do_List.setObjectName(u"menuTo_Do_List")
        self.menuMessage_Box = QMenu(self.menubar)
        self.menuMessage_Box.setObjectName(u"menuMessage_Box")
        self.menuExit = QMenu(self.menubar)
        self.menuExit.setObjectName(u"menuExit")
        self.menuEdit_Profile = QMenu(self.menubar)
        self.menuEdit_Profile.setObjectName(u"menuEdit_Profile")
        font25 = QFont()
        font25.setFamilies([u"MS Shell Dlg 2"])
        font25.setPointSize(16)
        font25.setBold(False)
        font25.setItalic(False)
        self.menuEdit_Profile.setFont(font25)
        self.menuAnnoiuncements = QMenu(self.menubar)
        self.menuAnnoiuncements.setObjectName(u"menuAnnoiuncements")
        MainWindow.setMenuBar(self.menubar)

        self.menubar.addAction(self.menuEdit_Profile.menuAction())
        self.menubar.addAction(self.menuAttandance.menuAction())
        self.menubar.addAction(self.menuMeetings.menuAction())
        self.menubar.addAction(self.menuTo_Do_List.menuAction())
        self.menubar.addAction(self.menuMessage_Box.menuAction())
        self.menubar.addAction(self.menuAnnoiuncements.menuAction())
        self.menubar.addAction(self.menuExit.menuAction())
        self.menuAttandance.addAction(self.menu21_t)
        self.menuAttandance.addAction(self.menu22_t)
        self.menuMeetings.addAction(self.menu31_t)
        self.menuMeetings.addAction(self.menu32_t_2)
        self.menuTo_Do_List.addAction(self.menu41_t)
        self.menuMessage_Box.addAction(self.menu51_t)
        self.menuExit.addAction(self.menu71_t)
        self.menuEdit_Profile.addAction(self.menu11_t)
        self.menuAnnoiuncements.addAction(self.announcementMenu)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(6)
        self.comboBox_instructor.setCurrentIndex(-1)
        self.comboBox_student.setCurrentIndex(-1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.menu11.setText(QCoreApplication.translate("MainWindow", u"Add Teacher", None))
        self.menu12.setText(QCoreApplication.translate("MainWindow", u"Edit Teacher", None))
        self.menu21.setText(QCoreApplication.translate("MainWindow", u"Add student", None))
        self.menu22.setText(QCoreApplication.translate("MainWindow", u"Edit student", None))
        self.menu31_t.setText(QCoreApplication.translate("MainWindow", u"Meeting Schedule", None))
        self.menu32_t.setText(QCoreApplication.translate("MainWindow", u"Edit Meeting Schedule", None))
        self.menu23_t.setText(QCoreApplication.translate("MainWindow", u"Edit Course Schedule", None))
        self.menu41_t.setText(QCoreApplication.translate("MainWindow", u"Add/Edit To Do List", None))
        self.menu51_t.setText(QCoreApplication.translate("MainWindow", u"Add/Edit Message", None))
        self.menu71_t.setText(QCoreApplication.translate("MainWindow", u"Logout", None))
        self.menu11_t.setText(QCoreApplication.translate("MainWindow", u"Edit Profile", None))
        self.actionAdd.setText(QCoreApplication.translate("MainWindow", u"Add", None))
        self.actionEdit.setText(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.actionAdd_2.setText(QCoreApplication.translate("MainWindow", u"Add", None))
        self.actionEdit_2.setText(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menu22_t_2.setText(QCoreApplication.translate("MainWindow", u"Edit Course", None))
        self.menu21_t.setText(QCoreApplication.translate("MainWindow", u"Lesson Schedule", None))
        self.menu22_t.setText(QCoreApplication.translate("MainWindow", u"Lesson Attendance", None))
        self.menu32_t_2.setText(QCoreApplication.translate("MainWindow", u"Meeting Attendance", None))
        self.announcementMenu.setText(QCoreApplication.translate("MainWindow", u"Add/Edit Announcement", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"    \ue736 SMART SCHOOL > School-Learning-Enhancement-System \ue736", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"You login as teacher !!!", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"   \ue736 WELCOME TO SMART SCHOOL 2.0 \ue736", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"Home", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"Surname", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Enter your current Password / Set a new Password", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"Email", None))
        self.b6.setText(QCoreApplication.translate("MainWindow", u"Update your details", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"Name", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"Phone", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"City", None))
        self.tb27.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Set password", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Edit your profile", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QCoreApplication.translate("MainWindow", u"Edit Profile", None))
        self.dateInput.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Please select a date for the lesson", None))
        self.lessonName.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Please add/select a a lesson", None))
        self.timeSlot.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Please enter a time slot; hh:mm-hh:mm", None))
        self.addLessonBtn.setText(QCoreApplication.translate("MainWindow", u"Add/Edit Lesson", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Add/Edit Lesson", None))
        self.deleteLessonBtn.setText(QCoreApplication.translate("MainWindow", u"Delete Lesson", None))
        self.deleteAllLessonsBtn.setText(QCoreApplication.translate("MainWindow", u"Delete All Lessons", None))
        ___qtablewidgetitem = self.lessonTable.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Lesson ID", None));
        ___qtablewidgetitem1 = self.lessonTable.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Lesson", None));
        ___qtablewidgetitem2 = self.lessonTable.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Date", None));
        ___qtablewidgetitem3 = self.lessonTable.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"Time Slot", None));
        ___qtablewidgetitem4 = self.lessonTable.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"Instructor", None));
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Lesson Date >", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Lesson Name >", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Lesson Time Slot >", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Lesson Schedule", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Select Instructor >", None))
        self.resetLessonBtn.setText(QCoreApplication.translate("MainWindow", u"Reset Form", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Lesson Schedule", None))
        self.label_57.setText(QCoreApplication.translate("MainWindow", u"Add/Edit Lesson Attandence Details", None))
        self.markAttendanceBtn.setText(QCoreApplication.translate("MainWindow", u"Save/Update", None))
        self.label_103.setText(QCoreApplication.translate("MainWindow", u"Select Lesson", None))
        self.label_109.setText(QCoreApplication.translate("MainWindow", u"Select Student", None))
        self.label_110.setText(QCoreApplication.translate("MainWindow", u"Mark Attendance", None))
        self.statusComboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"Present", None))
        self.statusComboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"Absent", None))
        self.statusComboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"Late", None))

        self.label_111.setText(QCoreApplication.translate("MainWindow", u"Attendance Records", None))
        self.deleteAttendanceBtn.setText(QCoreApplication.translate("MainWindow", u"Delete a selected record", None))
        self.deleteAllAttendanceBtn.setText(QCoreApplication.translate("MainWindow", u"Delete All Records", None))
        self.deleteSelectedStudentAttendanceBtn.setText(QCoreApplication.translate("MainWindow", u"Delete all records for the selected student", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_17), QCoreApplication.translate("MainWindow", u"Lesson Attendance", None))
        self.meetingDateInput.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Please select a date for a meeting", None))
        self.meetingTitle.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Please add a meeting", None))
        self.meetingTimeSlot.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Please enter a time slot; hh:mm-hh:mm", None))
        self.addMeetingBtn.setText(QCoreApplication.translate("MainWindow", u"Add/Edit Meeting", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Add/Edit a meeting", None))
        self.deleteMeetingBtn.setText(QCoreApplication.translate("MainWindow", u"Delete Meeting", None))
        self.deleteAllMeetingsBtn.setText(QCoreApplication.translate("MainWindow", u"Delete All Meetings", None))
        ___qtablewidgetitem5 = self.meetingTable.horizontalHeaderItem(0)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"Meeting Title", None));
        ___qtablewidgetitem6 = self.meetingTable.horizontalHeaderItem(1)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("MainWindow", u"Meeting Date", None));
        ___qtablewidgetitem7 = self.meetingTable.horizontalHeaderItem(2)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("MainWindow", u"Meeting Time", None));
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Meeting Date;", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Meeting Title;", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Meeting Time Slot;", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Meeting Schedule", None))
        self.resetMeetingBtn.setText(QCoreApplication.translate("MainWindow", u"Reset Form", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"Meeting Schedule", None))
        self.label_106.setText(QCoreApplication.translate("MainWindow", u"Add/Edit Meeting Attandence Details", None))
        self.deleteAttendanceBtn_2.setText(QCoreApplication.translate("MainWindow", u"Delete a selected record", None))
        self.label_112.setText(QCoreApplication.translate("MainWindow", u"Select Student", None))
        self.statusComboBox_2.setItemText(0, QCoreApplication.translate("MainWindow", u"Present", None))
        self.statusComboBox_2.setItemText(1, QCoreApplication.translate("MainWindow", u"Absent", None))
        self.statusComboBox_2.setItemText(2, QCoreApplication.translate("MainWindow", u"Late", None))

        self.deleteSelectedStudentAttendanceBtn_2.setText(QCoreApplication.translate("MainWindow", u"Delete all records for the selected student", None))
        self.label_113.setText(QCoreApplication.translate("MainWindow", u"Mark Attendance", None))
        self.markAttendanceBtn_2.setText(QCoreApplication.translate("MainWindow", u"Save/Update", None))
        self.label_114.setText(QCoreApplication.translate("MainWindow", u"Meeting Attendance Records", None))
        self.deleteAllAttendanceBtn_2.setText(QCoreApplication.translate("MainWindow", u"Delete All Records", None))
        self.label_104.setText(QCoreApplication.translate("MainWindow", u"Select Meeting", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), QCoreApplication.translate("MainWindow", u"Meeting Attendance", None))
        self.announcementTitle.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Please Type a Title", None))
        self.textEdit.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.addButton.setText(QCoreApplication.translate("MainWindow", u"Add", None))
        self.editButton.setText(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.deleteButton.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
        self.label_58.setText(QCoreApplication.translate("MainWindow", u"Add/Edit  Announcement Details", None))
        self.label_65.setText(QCoreApplication.translate("MainWindow", u"Announcements", None))
        self.announcementDate.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Please select a date for announcement", None))
        self.label_66.setText(QCoreApplication.translate("MainWindow", u"Select Deadline", None))
        self.label_67.setText(QCoreApplication.translate("MainWindow", u"Header", None))
        self.label_68.setText(QCoreApplication.translate("MainWindow", u"Announcement", None))
        self.label_69.setText(QCoreApplication.translate("MainWindow", u"Select Announcement for Edit", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Announcement", None))
        self.deadlineInput.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Please select a deadline", None))
        ___qtablewidgetitem8 = self.todoTable.horizontalHeaderItem(0)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("MainWindow", u"Task ID", None));
        ___qtablewidgetitem9 = self.todoTable.horizontalHeaderItem(1)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("MainWindow", u"Task", None));
        ___qtablewidgetitem10 = self.todoTable.horizontalHeaderItem(2)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("MainWindow", u"Deadline", None));
        ___qtablewidgetitem11 = self.todoTable.horizontalHeaderItem(3)
        ___qtablewidgetitem11.setText(QCoreApplication.translate("MainWindow", u"Status", None));
        ___qtablewidgetitem12 = self.todoTable.horizontalHeaderItem(4)
        ___qtablewidgetitem12.setText(QCoreApplication.translate("MainWindow", u"Created By", None));
        ___qtablewidgetitem13 = self.todoTable.horizontalHeaderItem(5)
        ___qtablewidgetitem13.setText(QCoreApplication.translate("MainWindow", u"Student", None));
        ___qtablewidgetitem14 = self.todoTable.horizontalHeaderItem(6)
        ___qtablewidgetitem14.setText(QCoreApplication.translate("MainWindow", u"Created Id", None));
        self.label_44.setText(QCoreApplication.translate("MainWindow", u"To :", None))
        self.todoName.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Type Here", None))
        self.deleteAllTodosBtn.setText(QCoreApplication.translate("MainWindow", u"Delete All Tasks", None))
        self.resAllTodoFields.setText(QCoreApplication.translate("MainWindow", u"Reset All Fields", None))
        self.label_42.setText(QCoreApplication.translate("MainWindow", u"Add/Edit Task", None))
        self.allTodosBtn.setText(QCoreApplication.translate("MainWindow", u"All", None))
        self.addTodoBtn.setText(QCoreApplication.translate("MainWindow", u"Save / Update", None))
        self.deleteTodoBtn.setText(QCoreApplication.translate("MainWindow", u"Delete Task", None))
        self.label_43.setText(QCoreApplication.translate("MainWindow", u"Add Task", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QCoreApplication.translate("MainWindow", u"To Do List", None))
        self.typeMessage.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Please Type Here", None))
        self.sendMessage.setText(QCoreApplication.translate("MainWindow", u"Send", None))
        self.label_105.setText(QCoreApplication.translate("MainWindow", u"Select  Person", None))
        self.label_107.setText(QCoreApplication.translate("MainWindow", u"Select  Chat", None))
        self.label_115.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:16pt;\">Chat Box</span></p></body></html>", None))
        self.username.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><br/></p></body></html>", None))
        self.usermail.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><br/></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), QCoreApplication.translate("MainWindow", u"Add Message", None))
        self.menuAttandance.setTitle(QCoreApplication.translate("MainWindow", u"Lessons", None))
        self.menuMeetings.setTitle(QCoreApplication.translate("MainWindow", u"Meetings", None))
        self.menuTo_Do_List.setTitle(QCoreApplication.translate("MainWindow", u"To Do List", None))
        self.menuMessage_Box.setTitle(QCoreApplication.translate("MainWindow", u"Message Box", None))
        self.menuExit.setTitle(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.menuEdit_Profile.setTitle(QCoreApplication.translate("MainWindow", u"Profile", None))
        self.menuAnnoiuncements.setTitle(QCoreApplication.translate("MainWindow", u"Announcements", None))
    # retranslateUi

