@echo off
REM Generated by trunk tool 'ruff'
set HOME=%HOME%
if not defined HOME set HOME=
set VIRTUAL_ENV=C:\Users\laptop\AppData\Local\trunk\tools\ruff\0.1.13-66e298bdac7039a7a93088e0e41013da
set PATH=C:\Users\laptop\AppData\Local\trunk\tools\ruff\0.1.13-66e298bdac7039a7a93088e0e41013da/bin;C:\Users\laptop\AppData\Local\trunk\tools\ruff\0.1.13-66e298bdac7039a7a93088e0e41013da/Scripts;C:\Users\laptop\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070/bin;C:\Users\laptop\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070;C:\Users\laptop\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\laptop\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%
set PYTHONUTF8=1

start /w /b ruff %*
