action_id: trunk-upgrade-available
date: 2024-01-17 19:04:43
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 0
  out: "notifications_to_delete:\r\n  - trunk-check-upgrade\r\n  - trunk-upgrade\r\n"
  err: ""
timestamp: 1705518283
full_timestamp:
  nanos: 217514000
  seconds: 1705518283
trunk_version: 1.19.0
action_output:
  notifications_to_delete:
    - trunk-check-upgrade
    - trunk-upgrade
