action_id: trunk-upgrade-available
date: 2024-01-17 12:04:51
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 0
  out: "notifications_to_delete:\r\n  - trunk-check-upgrade\r\n  - trunk-upgrade\r\n"
  err: ""
timestamp: 1705493091
full_timestamp:
  nanos: 454685000
  seconds: 1705493091
trunk_version: 1.19.0
action_output:
  notifications_to_delete:
    - trunk-check-upgrade
    - trunk-upgrade
