action_id: trunk-upgrade-available
date: 2024-01-19 01:42:07
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 0
  out: "notifications_to_delete:\r\n  - trunk-check-upgrade\r\n  - trunk-upgrade\r\n"
  err: ""
timestamp: 1705628527
full_timestamp:
  nanos: 270438000
  seconds: 1705628527
trunk_version: 1.19.0
action_output:
  notifications_to_delete:
    - trunk-check-upgrade
    - trunk-upgrade
