action_id: trunk-share-with-everyone
date: 2024-01-21 21:25:50
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 0
  out: "notifications_to_delete:\r\n  - trunk-share-with-everyone\r\n"
  err: ""
timestamp: 1705872350
full_timestamp:
  nanos: 186817000
  seconds: 1705872350
trunk_version: 1.19.0
action_output:
  notifications_to_delete:
    - trunk-share-with-everyone
